"""
Shared forecast engine for the demo UI.

Runs on the medical sales dataset (medical_sales_5yr_250k.csv, 2021-2025, real-shaped data
given to us, not generated by this project). The old BizWiz synthetic dataset and everything
that trained on it has been permanently deleted -- nothing here reads from it.

CHAMPIONS / DIMENSIONAL_CHAMPIONS are loaded from champions_medical.json /
champions_dimensional.json -- the literal output of score_whole_business.py and
score_dimensional.py's backtests, not a guess. Re-run those scripts and this file
automatically picks up the new result.

No regex/keyword matching lives in this file (or anywhere in the app)
anymore -- question understanding (metric, dimension, dimension_value,
explicit dates) is all done by parse_query() in llm_client.py, matched
against the real, dynamically-loaded DIMENSION_VALUES/METRIC_LABELS below.
This module only computes; it never parses free text.
"""
import json
import numpy as np
import pandas as pd

DATA_PATH = "medical_sales_5yr_250k.csv"
# A champion is still just "least-bad of 6 options" -- nothing before this stopped a value
# whose best-available model was itself measured to be badly wrong from answering with
# "confidence: high" anyway. Found live in champions_dimensional.json (Medical Product 0068,
# 81.2% MAPE, already answering questions before this floor existed) and pervasively at week
# grain for products (79.4% average champion MAPE, several individual champions over 100%,
# one over 300%). Applies to every dimensional lookup (week/month/year) -- not the 6
# whole-business slots, which have never shown this problem and are reviewed by hand, not
# swept over 302 values at a time.
DIMENSIONAL_MAX_RELIABLE_ERROR_PCT = 40


REASONS = {
    "naive_last_value": "repeats the last known value",
    "moving_avg": "averages the recent months/weeks",
    "linear_trend": "extrapolates the straight-line trend through 2021-2024",
    "seasonal_naive": "repeats the same period from one year back",
    "chronos": "Chronos-2, a pretrained forecasting model, run on the full 2021-2024 history",
    "claude-haiku-4-5": "Claude Haiku 4.5, given the full numeric history directly and asked "
                         "to predict the next value(s) -- only used where it won a real "
                         "backtest, the same rule every other candidate had to clear",
}

METRIC_COLUMNS = {"net_sales": "net_sales", "gross_sales": "gross_sales",
                   "quantity": "quantity", "profit": "profit"}
METRIC_LABELS = {"net_sales": "net sales", "gross_sales": "gross sales",
                  "quantity": "units sold", "profit": "profit"}

DIMENSION_COLUMNS = {"branch": "stock_branch", "route": "route", "category": "category",
                      "product_type": "product_type", "customer_type": "customer_type",
                      "product": "product", "supplier": "supplier", "customer": "customer_id"}
# Which dimensions have ANY validated backtest behind them (score_dimensional.py).
# Decided by eda_medical.py's density check, not assumed -- this data is far richer than the
# old BizWiz set (250K rows vs 6,885), so scope is meaningfully wider than the old "branch +
# route only": branch/route/category/product_type/customer_type/supplier all cleared a
# comfortable density bar, and product is included too (tested despite thinner density,
# scored honestly like everything else rather than excluded by assumption). customer stays
# excluded -- individual customers are too thin (~8 rows/month, min 1) to forecast at all,
# confirmed by the density check rather than assumed the way it was last time.
DIMENSIONS_WITH_BACKTEST = {"branch", "route", "category", "product_type", "customer_type",
                             "supplier", "product"}

ALL_MODELS = ["naive_last_value", "moving_avg", "linear_trend", "seasonal_naive", "chronos"]

# Playground-only metric set -- deliberately wider than METRIC_COLUMNS (adds discount_amount,
# and a derived "cost" = quantity * unit_cost) and deliberately NOT merged into METRIC_COLUMNS,
# because METRIC_COLUMNS staying exactly the set score_whole_business.py actually backtested is what makes
# answer_question()'s "unvalidated_metric" refusal meaningful. The playground bypasses that
# refusal on purpose (see run_playground_forecast) -- these extra metrics must never leak into
# the validated Q&A path.
PLAYGROUND_METRIC_COLUMNS = {"net_sales": "net_sales", "gross_sales": "gross_sales",
                              "quantity": "quantity", "profit": "profit",
                              "discount_amount": "discount_amount"}
PLAYGROUND_METRIC_LABELS = {"net_sales": "net sales", "gross_sales": "gross sales",
                             "quantity": "units sold", "profit": "profit",
                             "discount_amount": "discount given",
                             "cost": "cost of goods (qty × unit cost)"}
MAX_PLAYGROUND_PERIODS_AHEAD = 120  # ~10 years -- generous for stress-testing, bounded so a
                                     # malformed/extreme request can't hang the page indefinitely


def _load_champions():
    """CHAMPIONS[metric][horizon] -> {model, reason}. Only metrics that were
    actually backtested (score_whole_business.py's METRICS list) appear here at all --
    that absence, not a hardcoded "!= net_sales" check, is what makes
    answer_question() refuse an unvalidated metric now."""
    with open("champions_medical.json") as f:
        data = json.load(f)
    all_champions, all_results = data["champions"], data["results"]
    out = {}
    for metric, champions in all_champions.items():
        out[metric] = {}
        results = all_results[metric]
        for horizon, model in champions.items():
            if horizon == "year":
                score = f"{results['year'][model]['diff_pct']:+.1f}% vs. actual"
            else:
                score = f"{results[horizon][model]['mape']:.1f}% MAPE"
            out[metric][horizon] = {
                "model": model,
                "reason": f"{REASONS[model]} — won the {metric}/{horizon}-level "
                          f"2021-2024→2025 backtest ({score}).",
            }
    return out


def _load_dimensional_champions():
    """DIMENSIONAL_CHAMPIONS[dimension][value] -> {model, reason}, from
    score_dimensional.py's backtest (net_sales, monthly grain, across every dimension that
    cleared eda_medical.py's density check). A (dimension, value) pair NOT in here has no
    validated forecast -- that absence is what answer_question() checks, not a hardcoded
    dimension list."""
    try:
        with open("champions_dimensional.json") as f:
            data = json.load(f)
    except FileNotFoundError:
        return {}
    out = {}
    for dimension, values in data.items():
        out[dimension] = {}
        for value, info in values.items():
            model = info["champion"]
            score = info["scores"][model]
            out[dimension][value] = {
                "model": model, "error_pct": score,
                "reason": f"{REASONS[model]} — won the {dimension}={value} monthly "
                          f"2021-2024→2025 backtest ({score}% MAPE).",
            }
    return out


def _load_dimensional_yearly_champions():
    """DIMENSIONAL_YEARLY_CHAMPIONS[dimension][value] -> {model, reason}, from
    score_dimensional_yearly.py's backtest -- same values as DIMENSIONAL_CHAMPIONS, but scored
    on the FULL YEAR total (sum 12 predicted months, compare to the real 2025 year total)
    rather than month-to-month error. A value can have a different champion here than in
    DIMENSIONAL_CHAMPIONS -- being accurate month-to-month and being accurate on the annual
    total are different questions. A (dimension, value) pair NOT in here has no validated
    YEAR-level forecast -- answer_question() falls back to the existing next-month-only
    refusal for it. Optional file: returns {} until score_dimensional_yearly.py has been run."""
    try:
        with open("champions_dimensional_yearly.json") as f:
            data = json.load(f)
    except FileNotFoundError:
        return {}
    out = {}
    for dimension, values in data.items():
        out[dimension] = {}
        for value, info in values.items():
            model = info["champion"]
            diff = info["diff_pct"][model]
            out[dimension][value] = {
                "model": model, "error_pct": abs(diff),
                "reason": f"{REASONS[model]} — won the {dimension}={value} full-year "
                          f"2021-2024→2025 backtest ({diff:+.1f}% vs. actual).",
            }
    return out


def _load_dimension_values():
    """Real branch/route/category/product_type/customer_type/supplier/product names from the
    data -- fed to the LLM (parse_query) as the ground truth to match a question's text
    against, and used here to verify its answer isn't hallucinated. Pulled live from the CSV
    every call -- if a branch is added tomorrow, this picks it up automatically, nothing to
    hand-maintain. "customer" is deliberately absent (500 IDs, not names -- excluded from
    backtesting by the density check, and wouldn't be a meaningful list to match text
    against even if it weren't)."""
    df = pd.read_csv(DATA_PATH)
    return {
        "branch": sorted(df["stock_branch"].unique().tolist()),
        "route": sorted(df["route"].unique().tolist()),
        "category": sorted(df["category"].unique().tolist()),
        "product_type": sorted(df["product_type"].unique().tolist()),
        "customer_type": sorted(df["customer_type"].unique().tolist()),
        "supplier": sorted(df["supplier"].unique().tolist()),
        "product": sorted(df["product"].unique().tolist()),
    }


def _load_full_backtest_scores():
    """Every candidate's real backtest MAPE, not just the champion's -- the same
    champions_medical.json/champions_dimensional.json files already have every model's score
    (score_whole_business.py's "results", score_dimensional.py's "scores"), just not surfaced
    by _load_champions() above. Used by historical_mape() to give the Model Playground
    something real to compare a fresh prediction against, without recomputing anything."""
    with open("champions_medical.json") as f:
        whole = json.load(f)["results"]
    try:
        with open("champions_dimensional.json") as f:
            dimensional = json.load(f)
    except FileNotFoundError:
        dimensional = {}
    return whole, dimensional


def historical_mape(metric, freq, model_name, dimension=None, dimension_value=None):
    """The real MAPE score_whole_business.py/score_dimensional.py measured for this exact
    metric/dimension/model/horizon, or None if that combination was never backtested at all
    (an unvalidated metric like "cost", or a dimension/value score_dimensional.py skipped).
    Only week/month horizons are covered -- the Playground doesn't expose a "year" grain, and
    the saved year-level number is a different statistic (% diff on a full-year total, not a
    mean of per-period errors), not directly comparable to a MAPE."""
    if dimension and dimension_value:
        scores = FULL_RESULTS_DIMENSIONAL.get(dimension, {}).get(dimension_value, {}).get("scores", {})
        return scores.get(model_name)
    horizon = "week" if freq == "W" else "month"
    return FULL_RESULTS_WHOLE.get(metric, {}).get(horizon, {}).get(model_name, {}).get("mape")


CHAMPIONS = _load_champions()
DIMENSIONAL_CHAMPIONS = _load_dimensional_champions()
DIMENSIONAL_YEARLY_CHAMPIONS = _load_dimensional_yearly_champions()

def _load_dimensional_weekly_champions():
    """DIMENSIONAL_WEEKLY_CHAMPIONS[dimension][value] -> {model, reason}, from
    score_dimensional_weekly.py's backtest -- a SEPARATE, stricter-threshold population than
    DIMENSIONAL_CHAMPIONS (52 weeks of real test data required, vs 12 months), so a value can
    have a month/year champion but no week champion. Optional file: returns {} until
    score_dimensional_weekly.py has been run."""
    try:
        with open("champions_dimensional_weekly.json") as f:
            data = json.load(f)
    except FileNotFoundError:
        return {}
    out = {}
    for dimension, values in data.items():
        out[dimension] = {}
        for value, info in values.items():
            model = info["champion"]
            score = info["scores"][model]
            out[dimension][value] = {
                "model": model, "error_pct": score,
                "reason": f"{REASONS[model]} — won the {dimension}={value} weekly "
                          f"2021-2024→2025 backtest ({score}% MAPE).",
            }
    return out


DIMENSIONAL_WEEKLY_CHAMPIONS = _load_dimensional_weekly_champions()
DIMENSION_VALUES = _load_dimension_values()
FULL_RESULTS_WHOLE, FULL_RESULTS_DIMENSIONAL = _load_full_backtest_scores()


def load_series(freq="MS", metric="net_sales", dimension=None, dimension_value=None):
    column = METRIC_COLUMNS.get(metric, "net_sales")
    df = pd.read_csv(DATA_PATH, parse_dates=["sales_date"])
    if dimension and dimension_value:
        df = df[df[DIMENSION_COLUMNS[dimension]] == dimension_value]
    s = df.set_index("sales_date").resample(freq)[column].sum()
    if dimension and dimension_value and len(s):
        # A specific branch/route can have a genuinely zero-activity month --
        # reindex so the series stays continuous instead of silently skipping it.
        full_index = pd.date_range(s.index.min(), s.index.max(), freq=freq)
        s = s.reindex(full_index, fill_value=0.0)
    return s.iloc[1:-1] if freq == "W" else s  # trim partial edge weeks only


def load_playground_series(freq, metric, dimension=None, dimension_value=None):
    """Same shape as load_series(), but against PLAYGROUND_METRIC_COLUMNS' wider set --
    kept as its own function rather than widening load_series() itself, so the validated
    Q&A path can never accidentally reach a metric it never backtested."""
    df = pd.read_csv(DATA_PATH, parse_dates=["sales_date"])
    if dimension and dimension_value:
        df = df[df[DIMENSION_COLUMNS[dimension]] == dimension_value]
    if metric == "cost":
        df = df.assign(_pg_metric=df["quantity"] * df["unit_cost"])
        column = "_pg_metric"
    else:
        column = PLAYGROUND_METRIC_COLUMNS.get(metric, "net_sales")
    s = df.set_index("sales_date").resample(freq)[column].sum()
    if dimension and dimension_value and len(s):
        full_index = pd.date_range(s.index.min(), s.index.max(), freq=freq)
        s = s.reindex(full_index, fill_value=0.0)
    return s.iloc[1:-1] if freq == "W" else s


def run_playground_forecast(metric, dimension, dimension_value, target_year=None,
                             target_month=None, periods_ahead=None, freq="MS", log_fn=None):
    """Direct model-testing tool -- deliberately bypasses the validation gate
    answer_question() enforces. Runs every candidate in ALL_MODELS on ANY metric/dimension
    combination, including ones never backtested, and can push a forecast further out than
    Phase 1's normal "next month only" limit. The point is to see raw numbers for
    combinations that haven't been proven yet, or to stress a validated one past its normal
    scope -- clearly separate from the "only show what's actually been proven" guarantee the
    main Q&A path keeps.

    Every malformed-input problem (bad dimension_value, multiple/non-numeric year, a target
    too far out, not enough history) comes back as {"error": "..."} rather than raising --
    the caller shows that string directly rather than crashing. A per-candidate forecast
    failure (e.g. a model needing more history than is available) lands in the "failures"
    dict instead of aborting the other candidates.

    If the resolved target period is already inside the recorded data, this runs a genuine
    ad-hoc backtest instead of refusing: each candidate trains ONLY on data strictly before
    that period, and the result includes the real recorded value alongside every prediction,
    so a past period can be used to see how each model would actually have done.
    """
    log_fn = log_fn or (lambda m: None)

    if dimension:
        if dimension not in (set(DIMENSION_VALUES) | {"customer"}):
            return {"error": f"{dimension!r} isn't a real dimension type."}
        real_values = DIMENSION_VALUES.get(dimension, [])
        normalized = str(dimension_value or "").strip()
        if not normalized:
            return {"error": f"Pick a specific {dimension} -- leave the value blank only when "
                              f"dimension is 'Whole business'.",
                    "valid_values": real_values}
        if not real_values:
            return {"error": f"No {dimension} list is loaded to match against yet -- "
                              f"nothing typed here can be verified."}
        match = next((v for v in real_values if v.casefold() == normalized.casefold()), None)
        if not match:
            return {"error": f"{dimension_value!r} isn't a real {dimension} -- no match "
                              f"(case-insensitive) in the data.",
                    "valid_values": real_values}
        dimension_value = match  # normalized to the real, correctly-cased value
    else:
        dimension_value = None

    if metric not in PLAYGROUND_METRIC_COLUMNS and metric != "cost":
        return {"error": f"{metric!r} isn't a real metric/column."}

    # An explicit year/month always resolves at monthly grain -- Phase 1's own dimensional
    # champions are monthly-only, and "which week of that month" has no single answer anyway.
    if target_year is not None or target_month is not None:
        freq = "MS"

    full_series = load_playground_series(freq, metric, dimension, dimension_value)
    log_fn(f"playground: loaded {len(full_series)} points for metric={metric!r} "
           f"dimension={dimension!r} value={dimension_value!r} freq={freq!r}")
    if len(full_series) < 2:
        return {"error": f"Only {len(full_series)} data point(s) exist for this combination -- "
                          f"not enough history to forecast anything."}
    last_date = full_series.index.max()
    offset = pd.DateOffset(weeks=1) if freq == "W" else pd.DateOffset(months=1)

    def _periods_between(start, end):
        # A DateOffset has no fixed length (a month isn't a constant number of days), so a
        # Timedelta can't be divided by one -- count in calendar units instead, same pattern
        # answer_question() already uses for months_ahead/years_ahead above.
        if freq == "W":
            return int(round((end - start).days / 7))
        return (end.year - start.year) * 12 + (end.month - start.month)

    is_backtest, actual_value = False, None
    year_only = False
    if target_year is not None or target_month is not None:
        year_only = target_month is None
        if not year_only:
            year = target_year or (last_date.year if target_month <= last_date.month else last_date.year + 1)
            target_period = pd.Timestamp(year=year, month=target_month, day=1)
        else:
            target_period = pd.Timestamp(year=target_year, month=12, day=1)  # year-only -> December of that year

        if target_period <= last_date:
            is_backtest = True
            # Year-only means "the full year," same as everywhere else in this app -- train on
            # everything through the END OF THE PRIOR YEAR and forecast all 12 months, so the
            # backtest compares a genuine 12-month path, not just December's single value. A
            # specific month stays a single-point target (train through 1 period before it).
            train_end = pd.Timestamp(year=target_year - 1, month=12, day=1) if year_only else target_period - offset
            train_series = full_series.loc[:train_end]
            if year_only:
                # "actual" for a full-year target is the year's total, not December's single
                # month -- matches how answer_question()'s year branch and
                # score_whole_business.py's year-level backtest both already define it.
                year_actuals = full_series.loc[pd.Timestamp(year=target_year, month=1, day=1):target_period]
                actual_value = float(year_actuals.sum()) if len(year_actuals) == 12 else None
            elif target_period in full_series.index:
                actual_value = float(full_series.loc[target_period])
            if len(train_series) < 2:
                return {"error": f"Only {len(train_series)} point(s) of history exist before "
                                  f"{train_end.strftime('%b %Y')} -- too early to have "
                                  f"trained anything on yet."}
            periods_ahead = _periods_between(train_series.index.max(), target_period)
        else:
            train_series = full_series
            periods_ahead = _periods_between(last_date, target_period)
    else:
        train_series = full_series
        periods_ahead = periods_ahead or 1
        target_period = last_date + offset * periods_ahead

    if periods_ahead < 1:
        return {"error": "That period is already fully covered by the training data used -- "
                          "pick something further ahead to actually test a forecast."}
    if periods_ahead > MAX_PLAYGROUND_PERIODS_AHEAD:
        return {"error": f"{periods_ahead} periods ahead is too far for this tool (capped at "
                          f"{MAX_PLAYGROUND_PERIODS_AHEAD}) -- pick something closer."}

    # Full actual path for the backtest case -- lets MAPE below be computed across every
    # period_ahead step, not just the final one, when more than one period was requested.
    actual_path = None
    if is_backtest:
        actual_path = full_series.loc[train_series.index.max() + offset:target_period].values

    def _mape(actual_arr, pred_arr):
        actual_arr, pred_arr = np.asarray(actual_arr, dtype=float), np.asarray(pred_arr, dtype=float)
        if np.any(actual_arr == 0):  # avoid div-by-zero -- same fallback already used in score_dimensional.py
            return float(np.mean(np.abs(actual_arr - pred_arr)) / (np.mean(np.abs(actual_arr)) + 1e-9) * 100)
        return float(np.mean(np.abs((actual_arr - pred_arr) / actual_arr)) * 100)

    predictions, failures = {}, {}
    for name in ALL_MODELS:
        try:
            pred = run_forecast(name, train_series, periods_ahead, freq, log_fn=log_fn,
                                 metric_label=METRIC_LABELS.get(metric, metric),
                                 dimension=dimension, dimension_value=dimension_value)
            if year_only:
                # The headline number for a full-year target is the year's total, not
                # December's single month -- same reasoning as actual_value above. MAPE
                # becomes "% off on the annual total" (score_whole_business.py's own
                # year-level statistic), not a mean of 12 separate monthly errors, which
                # can look worse than the total actually is when over/under months offset.
                value = float(np.sum(pred[-12:]))
                live_mape = (abs((actual_value - value) / actual_value) * 100
                             if actual_value else None)
            else:
                value = float(pred[-1])
                live_mape = (_mape(actual_path, pred)
                             if actual_path is not None and len(actual_path) == len(pred) else None)
            predictions[name] = {
                "value": value,
                "live_mape": live_mape,
                "historical_mape": historical_mape(metric, freq, name, dimension, dimension_value),
            }
        except Exception as e:
            log_fn(f"playground: {name} failed -- {type(e).__name__}: {e}")
            failures[name] = f"{type(e).__name__}: {e}"

    return {
        "error": None, "metric": metric, "dimension": dimension, "dimension_value": dimension_value,
        "history": train_series, "target_period": target_period, "periods_ahead": periods_ahead,
        "freq": freq, "is_backtest": is_backtest, "actual_value": actual_value, "year_only": year_only,
        "predictions": predictions, "failures": failures,
    }


def _emit(log_fn, msg):
    (log_fn or (lambda m: print(f"[model] {m}")))(msg)


def run_forecast(model_name, train_series, horizon, freq="W", log_fn=None,
                  metric_label=None, dimension=None, dimension_value=None):
    """metric_label/dimension/dimension_value are only consumed by the claude-haiku-4-5
    branch -- they tell the LLM what its numbers actually measure and which slice they
    cover. The 5 local models ignore them (a least-squares fit doesn't care what the
    column is called). They're optional so the offline scoring scripts and validate_2025.py
    keep working unchanged, but every live call site passes them."""
    cycle = 52 if freq == "W" else 12
    _emit(log_fn, f"MODEL INPUT: model={model_name!r} freq={freq!r} horizon={horizon} "
                   f"history={len(train_series)} points, last 6: {list(np.round(train_series.values[-6:], 1))}")

    if model_name == "naive_last_value":
        pred = np.full(horizon, train_series.iloc[-1])
    elif model_name == "moving_avg":
        window = 8 if freq == "W" else 3
        pred = np.full(horizon, train_series.iloc[-window:].mean())
    elif model_name == "linear_trend":
        x = np.arange(len(train_series))
        slope, intercept = np.polyfit(x, train_series.values, 1)
        fx = np.arange(len(train_series), len(train_series) + horizon)
        pred = slope * fx + intercept
    elif model_name == "seasonal_naive":
        end = -cycle + horizon
        pred = train_series.iloc[-cycle:end if end < 0 else None].values[:horizon]
    elif model_name == "chronos":
        from chronos import Chronos2Pipeline
        input_df = pd.DataFrame({"item_id": "business", "timestamp": train_series.index,
                                  "target": train_series.values})
        pipe = Chronos2Pipeline.from_pretrained("amazon/chronos-2")
        out = pipe.predict_df(input_df, prediction_length=horizon, freq=freq)
        pred = out["predictions"].values[:horizon]
    elif model_name == "claude-haiku-4-5":
        # The LLM candidate -- only reachable here if it actually won a real backtest for
        # this exact metric/horizon (score_whole_business.py / score_dimensional.py), same
        # rule every other candidate had to clear. Real cost per call now, unlike the 5
        # local candidates -- see llm_client.py for why this stays out of the Model
        # Playground's ALL_MODELS list (kept bounded to backtested, live-answer use only).
        from llm_client import llm_predict
        period_label = "weekly" if freq == "W" else "monthly"
        # metric_label passed through as-is, including None: llm_predict then says "the
        # series" rather than asserting a metric nobody told it about. Defaulting to
        # "net sales" here is exactly the bug this integration fixed.
        pred = np.asarray(llm_predict(
            list(train_series.values), horizon, period_label, metric_label=metric_label,
            dimension=dimension, dimension_value=dimension_value, log_fn=log_fn))
    else:
        raise ValueError(f"unknown model_name: {model_name}")

    _emit(log_fn, f"MODEL OUTPUT (raw): {list(np.round(np.asarray(pred), 1))}")
    return pred


def run_forecast_with_range(model_name, train_series, horizon, freq="W", log_fn=None,
                             metric_label=None, dimension=None, dimension_value=None):
    """Same as run_forecast, but also returns a (low, high) 80% range per step
    when the model actually produces one (Chronos-2's own quantiles) -- (None,
    None) per step otherwise."""
    _emit(log_fn, f"MODEL INPUT: model={model_name!r} freq={freq!r} horizon={horizon} "
                   f"history={len(train_series)} points, last 6: {list(np.round(train_series.values[-6:], 1))}")
    if model_name == "chronos":
        from chronos import Chronos2Pipeline
        input_df = pd.DataFrame({"item_id": "business", "timestamp": train_series.index,
                                  "target": train_series.values})
        pipe = Chronos2Pipeline.from_pretrained("amazon/chronos-2")
        out = pipe.predict_df(input_df, prediction_length=horizon, freq=freq)
        pred, lo, hi = out["predictions"].values[:horizon], out["0.1"].values[:horizon], out["0.9"].values[:horizon]
        _emit(log_fn, f"MODEL OUTPUT (raw): pred={list(np.round(pred, 1))} "
                       f"lo={list(np.round(lo, 1))} hi={list(np.round(hi, 1))}")
        return pred, lo, hi
    pred = run_forecast(model_name, train_series, horizon, freq, log_fn=log_fn,
                         metric_label=metric_label, dimension=dimension,
                         dimension_value=dimension_value)
    return pred, np.full(horizon, np.nan), np.full(horizon, np.nan)


def confidence_note(years_ahead):
    if years_ahead <= 1:
        return "high", "this is the exact horizon that was backtested"
    if years_ahead <= 3:
        return "moderate", (f"this is {years_ahead} years beyond the backtested horizon -- "
                             f"extrapolated, not directly validated")
    return "low", (f"this is {years_ahead} years beyond the backtested horizon -- "
                    f"well past what's been tested; treat as a rough extrapolation, not a prediction to plan around")


def month_confidence_note(months_ahead):
    if months_ahead <= 1:
        return "high", "this is the exact horizon that was backtested"
    if months_ahead <= 6:
        return "moderate", (f"this is {months_ahead} months beyond the backtested horizon -- "
                             f"extrapolated, not directly validated")
    return "low", (f"this is {months_ahead} months beyond the backtested horizon -- "
                    f"well past what's been tested; treat as a rough extrapolation, not a prediction to plan around")


def _log(steps, msg):
    print(f"[answer_question] {msg}")
    steps.append(msg)


def answer_question(horizon, target_year=None, target_month=None, metric="net_sales",
                     dimension=None, dimension_value=None):
    """horizon in {'week','month','year'}; target_year/target_month optional;
    metric in METRIC_COLUMNS; dimension+dimension_value optional (e.g.
    ("branch", "Vaughan")) -> dict with predicted_value, model_name, reason,
    series, is_actual, period_label, out_of_range, metric, log.

    Dimension handling (Phase 1 -- see score_dimensional.py):
    - No dimension: whole-business, exactly as before.
    - Dimension + value WITH a validated backtest (currently branch/route
      only, from DIMENSIONS_WITH_BACKTEST + DIMENSIONAL_CHAMPIONS): actual
      lookups work for any period; FORECASTS are scoped to "next month" only
      for now, matching exactly what was backtested -- multi-period-ahead
      dimensional forecasting is a real future extension, not built yet.
    - Dimension + value with NO validated backtest (category/product/
      supplier/customer, or a value score_dimensional.py skipped for
      insufficient data): refused, same honest "not built yet" message as
      before -- just now driven by which dimensions actually have entries
      in DIMENSIONAL_CHAMPIONS, not a hardcoded "always refuse" rule.
    """
    steps = []
    log_fn = lambda msg: _log(steps, msg)  # noqa: E731
    metric_label = METRIC_LABELS.get(metric, metric)
    freq = "W" if horizon == "week" else "MS"

    _log(steps, f"horizon={horizon!r} target_year={target_year!r} target_month={target_month!r} "
                 f"metric={metric!r} dimension={dimension!r} dimension_value={dimension_value!r}")

    # ---------------- Dimensional path ----------------
    if dimension and dimension_value:
        has_backtest = (dimension in DIMENSIONS_WITH_BACKTEST
                         and dimension_value in DIMENSIONAL_CHAMPIONS.get(dimension, {}))
        _log(steps, f"dimension={dimension} is in Phase 1 (branch/route)? "
                     f"{dimension in DIMENSIONS_WITH_BACKTEST} | has a validated champion for "
                     f"{dimension_value!r}? {has_backtest}")

        series = load_series("MS", metric, dimension, dimension_value)  # Phase 1 = monthly only

        # Actual lookups always work, any dimension, any metric -- it's a real sum, not a model.
        if target_year is not None or target_month is not None:
            if target_month is not None:
                resolved_year = target_year or (series.index.max().year
                                                 if target_month <= series.index.max().month
                                                 else series.index.max().year + 1)
                target_period = pd.Timestamp(year=resolved_year, month=target_month, day=1)
                period_label = f"{target_period.strftime('%B %Y')} ({dimension}={dimension_value})"
            else:
                target_period = None
                period_label = f"{target_year} ({dimension}={dimension_value})"

            if target_period is not None and target_period in series.index:
                val = float(series.loc[target_period])
                _log(steps, f"{period_label} is a real recorded month -> actual {metric_label} {val:,.1f}")
                return {"predicted_value": val, "model_name": None,
                        "reason": f"Directly summed {metric_label} for {dimension}={dimension_value} "
                                  f"-- not modeled.",
                        "series": series, "is_actual": True, "period_label": period_label,
                        "out_of_range": False, "metric": metric, "log": steps}
            if target_period is None and target_year in series.index.year.values:
                val = float(series[series.index.year == target_year].sum())
                _log(steps, f"{period_label} is a real recorded year -> actual {metric_label} {val:,.1f}")
                return {"predicted_value": val, "model_name": None,
                        "reason": f"Directly summed {metric_label} for {dimension}={dimension_value} "
                                  f"-- not modeled.",
                        "series": series, "is_actual": True, "period_label": period_label,
                        "out_of_range": False, "metric": metric, "log": steps}

            # A pure year target (no specific month) with a validated YEAR-level champion for
            # this exact (dimension, value) -- score_dimensional_yearly.py's backtest, separate
            # from the month-level one above (a value can win one and not the other). Everything
            # else -- a month beyond next month, or a year with no yearly champion -- still
            # refuses exactly as before.
            yearly_champ = (target_month is None
                             and DIMENSIONAL_YEARLY_CHAMPIONS.get(dimension, {}).get(dimension_value))
            if yearly_champ:
                if yearly_champ["error_pct"] > DIMENSIONAL_MAX_RELIABLE_ERROR_PCT:
                    _log(steps, f"{dimension}={dimension_value} HAS a year champion "
                                 f"({yearly_champ['model']}) but its own backtested error "
                                 f"({yearly_champ['error_pct']:.1f}%) exceeds the "
                                 f"{DIMENSIONAL_MAX_RELIABLE_ERROR_PCT}% reliability floor -> "
                                 f"refusing rather than answering with a number already proven unreliable")
                    return {"predicted_value": None, "model_name": None, "reason": None,
                            "series": series, "is_actual": False, "period_label": period_label,
                            "out_of_range": True, "metric": metric,
                            "champion_too_unreliable": True, "log": steps}
                last_date = series.index.max()
                years_ahead = target_year - last_date.year
                model_name, reason = yearly_champ["model"], yearly_champ["reason"]
                months_needed = years_ahead * 12
                _log(steps, f"{dimension}={dimension_value} has a validated YEAR champion "
                             f"({model_name}) -> running it {months_needed} month(s) ahead to "
                             f"cover {target_year}")
                pred, lo, hi = run_forecast_with_range(model_name, series, months_needed, "MS",
                                                        log_fn=log_fn, metric_label=metric_label,
                                                        dimension=dimension,
                                                        dimension_value=dimension_value)
                target_months_pred = pred[-12:]
                predicted_value = float(np.sum(target_months_pred))
                range_low = float(np.nansum(lo[-12:])) if not np.all(np.isnan(lo)) else None
                range_high = float(np.nansum(hi[-12:])) if not np.all(np.isnan(hi)) else None
                level, why = confidence_note(years_ahead)
                _log(steps, f"{target_year} total for {dimension}={dimension_value}: "
                             f"{predicted_value:,.1f}  confidence={level} -- {why}")
                return {"predicted_value": predicted_value, "model_name": model_name,
                        "reason": reason + f" Extrapolated {years_ahead} extra year(s) past "
                                            f"that to reach {target_year}.",
                        "series": series, "is_actual": False, "period_label": period_label,
                        "out_of_range": False, "metric": metric, "years_ahead": years_ahead,
                        "confidence_level": level, "confidence_reason": why,
                        "range_low": range_low, "range_high": range_high, "log": steps}

            _log(steps, f"{period_label} isn't a recorded period, and dimensional forecasting "
                         f"beyond 'next month' isn't built yet -> refusing")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": period_label,
                    "out_of_range": True, "metric": metric,
                    "dimension_forecast_out_of_range": True, "log": steps}

        if not has_backtest or metric != "net_sales":
            _log(steps, f"no validated forecast for {dimension}={dimension_value!r}, metric={metric!r} -> refusing")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": None,
                    "out_of_range": True, "metric": metric,
                    "unvalidated_dimension": True, "log": steps}

        if horizon == "week":
            # A fully separate validation axis from the month/year champions below -- many
            # values (especially individual products) that clear the monthly bar don't clear
            # weekly's stricter one (52 real weeks vs 12 months). Absence here is an honest
            # refusal, never a silent substitution of the monthly champion for a week question
            # -- that silent substitution is exactly what this branch replaces (previously
            # "next week" for a dimension quietly answered with a monthly forecast).
            weekly_champ = DIMENSIONAL_WEEKLY_CHAMPIONS.get(dimension, {}).get(dimension_value)
            if not weekly_champ:
                _log(steps, f"no validated WEEK-level forecast for {dimension}={dimension_value!r} -> refusing")
                return {"predicted_value": None, "model_name": None, "reason": None,
                        "series": series, "is_actual": False, "period_label": None,
                        "out_of_range": True, "metric": metric,
                        "unvalidated_dimension": True, "log": steps}
            if weekly_champ["error_pct"] > DIMENSIONAL_MAX_RELIABLE_ERROR_PCT:
                _log(steps, f"{dimension}={dimension_value} HAS a week champion "
                             f"({weekly_champ['model']}) but its own backtested error "
                             f"({weekly_champ['error_pct']:.1f}%) exceeds the "
                             f"{DIMENSIONAL_MAX_RELIABLE_ERROR_PCT}% reliability floor -> "
                             f"refusing rather than answering with a number already proven unreliable")
                return {"predicted_value": None, "model_name": None, "reason": None,
                        "series": series, "is_actual": False, "period_label": None,
                        "out_of_range": True, "metric": metric,
                        "champion_too_unreliable": True, "log": steps}
            weekly_series = load_series("W", metric, dimension, dimension_value)
            model_name, reason = weekly_champ["model"], weekly_champ["reason"]
            pred = run_forecast(model_name, weekly_series, 1, "W", log_fn=log_fn,
                                 metric_label=metric_label, dimension=dimension,
                                 dimension_value=dimension_value)
            predicted_value = float(pred[0])
            period_label = ("week of " + (weekly_series.index.max() + pd.Timedelta(weeks=1)).strftime("%b %d, %Y")
                             + f" ({dimension}={dimension_value})")
            _log(steps, f"-> {period_label}: {predicted_value:,.1f}")
            return {"predicted_value": predicted_value, "model_name": model_name, "reason": reason,
                    "series": weekly_series, "is_actual": False, "period_label": period_label,
                    "out_of_range": False, "metric": metric, "weeks_ahead": 1,
                    "confidence_level": "high", "confidence_reason": "this is the exact horizon that was backtested",
                    "range_low": None, "range_high": None, "log": steps}

        champ = DIMENSIONAL_CHAMPIONS[dimension][dimension_value]
        if champ["error_pct"] > DIMENSIONAL_MAX_RELIABLE_ERROR_PCT:
            _log(steps, f"{dimension}={dimension_value} HAS a month champion "
                         f"({champ['model']}) but its own backtested error "
                         f"({champ['error_pct']:.1f}%) exceeds the "
                         f"{DIMENSIONAL_MAX_RELIABLE_ERROR_PCT}% reliability floor -> "
                         f"refusing rather than answering with a number already proven unreliable")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": None,
                    "out_of_range": True, "metric": metric,
                    "champion_too_unreliable": True, "log": steps}
        model_name, reason = champ["model"], champ["reason"]
        pred = run_forecast(model_name, series, 1, "MS", log_fn=log_fn,
                             metric_label=metric_label, dimension=dimension,
                             dimension_value=dimension_value)
        predicted_value = float(pred[0])
        period_label = f"{(series.index.max() + pd.DateOffset(months=1)).strftime('%B %Y')} ({dimension}={dimension_value})"
        _log(steps, f"-> {period_label}: {predicted_value:,.1f}")
        return {"predicted_value": predicted_value, "model_name": model_name, "reason": reason,
                "series": series, "is_actual": False, "period_label": period_label,
                "out_of_range": False, "metric": metric, "months_ahead": 1,
                "confidence_level": "high", "confidence_reason": "this is the exact horizon that was backtested",
                "range_low": None, "range_high": None, "log": steps}

    # ---------------- Whole-business path (unchanged logic, dynamic metric check) ----------------
    series = load_series(freq, metric)
    champ = CHAMPIONS.get(metric, {}).get(horizon)
    model_name, reason = (champ["model"], champ["reason"]) if champ else (None, None)

    if horizon == "month" and target_month is not None:
        monthly = load_series("MS", metric)
        last_date = monthly.index.max()
        if target_year is None:
            resolved_year = last_date.year if target_month > last_date.month else last_date.year + 1
            _log(steps, f"no explicit year given for month={target_month} -> resolved to "
                         f"{resolved_year} relative to data ending {last_date.strftime('%B %Y')}")
        else:
            resolved_year = target_year

        target_period = pd.Timestamp(year=resolved_year, month=target_month, day=1)
        is_in_data = target_period in monthly.index
        _log(steps, f"target month = {target_period.strftime('%B %Y')}; already in data? {is_in_data}")

        if is_in_data:
            actual_value = float(monthly.loc[target_period])
            _log(steps, f"{target_period.strftime('%B %Y')} is a real recorded month -> returning actual "
                         f"{metric_label} {actual_value:,.1f}, no model run")
            return {"predicted_value": actual_value, "model_name": None,
                    "reason": f"Directly summed {metric_label} from recorded transactions for that month -- not modeled.",
                    "series": series, "is_actual": True, "period_label": target_period.strftime("%B %Y"),
                    "out_of_range": False, "metric": metric, "months_ahead": 0, "log": steps}

        if not champ:
            _log(steps, f"metric={metric!r} has no backtest at all -> refusing regardless of months_ahead")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": target_period.strftime("%B %Y"),
                    "out_of_range": True, "metric": metric, "unvalidated_metric": True, "log": steps}

        months_ahead = (target_period.year - last_date.year) * 12 + (target_period.month - last_date.month)
        _log(steps, f"running {model_name} {months_ahead} month(s) ahead to reach {target_period.strftime('%B %Y')}")
        pred, lo, hi = run_forecast_with_range(model_name, series, months_ahead, "MS",
                                                log_fn=log_fn, metric_label=metric_label)
        predicted_value = float(pred[-1])
        range_low = float(lo[-1]) if not np.isnan(lo[-1]) else None
        range_high = float(hi[-1]) if not np.isnan(hi[-1]) else None
        _log(steps, f"{target_period.strftime('%B %Y')}: {predicted_value:,.1f}"
                     + (f"  (80% range: {range_low:,.1f} - {range_high:,.1f})" if range_low else "  (no range available for this method)"))
        level, why = month_confidence_note(months_ahead)
        _log(steps, f"confidence: {level} -- {why}")
        return {"predicted_value": predicted_value, "model_name": model_name,
                "reason": reason + f" Extrapolated {months_ahead} month(s) ahead to reach {target_period.strftime('%B %Y')}.",
                "series": series, "is_actual": False, "period_label": target_period.strftime("%B %Y"),
                "out_of_range": False, "metric": metric, "months_ahead": months_ahead,
                "confidence_level": level, "confidence_reason": why,
                "range_low": range_low, "range_high": range_high, "log": steps}

    if horizon == "year" and target_year is not None:
        monthly = load_series("MS", metric)
        counts = monthly.groupby(monthly.index.year).size()
        last_year, last_month = monthly.index.max().year, monthly.index.max().month
        year_is_complete = target_year in counts.index and (
            counts[target_year] == 12 if target_year < last_year
            else (target_year == last_year and last_month == 12)
        )
        _log(steps, f"data fully covers through {last_year}-{last_month:02d}; "
                     f"is {target_year} already complete in the data? {year_is_complete}")
        if year_is_complete:
            actual_value = float(monthly[monthly.index.year == target_year].sum())
            _log(steps, f"{target_year} is a real recorded year -> returning actual "
                         f"{metric_label} {actual_value:,.1f}, no model run")
            return {"predicted_value": actual_value, "model_name": None,
                    "reason": f"Directly summed {metric_label} from recorded transactions for that year -- not modeled.",
                    "series": series, "is_actual": True, "period_label": str(target_year),
                    "out_of_range": False, "metric": metric, "log": steps}

        years_ahead = target_year - last_year
        _log(steps, f"{target_year} is {years_ahead} year(s) beyond the data -> forecasting it, honestly labeled")

        if not champ:
            _log(steps, f"metric={metric!r} has no backtest at all -> refusing regardless of years_ahead")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": str(target_year),
                    "out_of_range": True, "metric": metric, "unvalidated_metric": True, "log": steps}

        months_needed = years_ahead * 12
        _log(steps, f"running {model_name} {months_needed} months ahead "
                     f"(covers {last_year + 1} through {target_year}), then keeping only {target_year}'s 12 months")
        pred, lo, hi = run_forecast_with_range(model_name, series, months_needed, "MS",
                                                log_fn=log_fn, metric_label=metric_label)
        target_months_pred = pred[-12:]
        predicted_value = float(np.sum(target_months_pred))
        range_low = float(np.nansum(lo[-12:])) if not np.all(np.isnan(lo)) else None
        range_high = float(np.nansum(hi[-12:])) if not np.all(np.isnan(hi)) else None
        _log(steps, f"{target_year} total: {predicted_value:,.1f}"
                     + (f"  (80% range: {range_low:,.1f} - {range_high:,.1f})" if range_low else "  (no range available for this method)"))
        level, why = confidence_note(years_ahead)
        _log(steps, f"confidence: {level} -- {why}")
        return {"predicted_value": predicted_value, "model_name": model_name,
                "reason": reason + f" Extrapolated {years_ahead} extra year(s) past that to reach {target_year}.",
                "series": series, "is_actual": False, "period_label": str(target_year),
                "out_of_range": False, "metric": metric, "years_ahead": years_ahead,
                "confidence_level": level, "confidence_reason": why,
                "range_low": range_low, "range_high": range_high, "log": steps}

    if not champ:
        _log(steps, f"metric={metric!r} has no backtest (validated metrics: {list(CHAMPIONS.keys())}) "
                     f"-> refusing")
        return {"predicted_value": None, "model_name": None, "reason": None,
                "series": series, "is_actual": False, "period_label": None,
                "out_of_range": True, "metric": metric, "unvalidated_metric": True, "log": steps}

    steps_ahead = 12 if horizon == "year" else 1
    _log(steps, f"running {model_name} on {len(series)} periods of history, {steps_ahead} step(s) ahead")
    pred = run_forecast(model_name, series, steps_ahead, freq, log_fn=log_fn,
                         metric_label=metric_label)
    predicted_value = float(np.sum(pred)) if horizon == "year" else float(pred[0])
    _log(steps, f"-> final predicted_value: {predicted_value:,.1f}")

    last_date = series.index.max()
    if horizon == "year":
        period_label = str(last_date.year + 1)
    elif horizon == "month":
        period_label = (last_date + pd.DateOffset(months=1)).strftime("%B %Y")
    else:
        period_label = "week of " + (last_date + pd.Timedelta(weeks=1)).strftime("%b %d, %Y")
    _log(steps, f"this forecast covers: {period_label}")

    return {"predicted_value": predicted_value, "model_name": model_name, "reason": reason,
            "series": series, "is_actual": False, "period_label": period_label,
            "out_of_range": False, "metric": metric, "years_ahead": 1,
            "confidence_level": "high", "confidence_reason": "this is the exact horizon that was backtested",
            "range_low": None, "range_high": None, "log": steps}
