"""
Shared forecast engine for the demo UI.

Runs on the medical sales dataset (medical_sales_5yr_250k.csv, 2021-2025, real-shaped data
given to us, not generated by this project). The old BizWiz synthetic dataset and everything
that trained on it has been permanently deleted -- nothing here reads from it.

CHAMPIONS / DIMENSIONAL_CHAMPIONS are loaded from champions_medical.json /
champions_dimensional.json -- the literal output of score_whole_business.py and
score_dimensional.py's backtests, not a guess. Re-run those scripts and this file
automatically picks up the new result.

No regex/keyword matching lives in this file (or anywhere in the app)
anymore -- question understanding (metric, dimension, dimension_value,
explicit dates) is all done by parse_query() in llm_client.py, matched
against the real, dynamically-loaded DIMENSION_VALUES/METRIC_LABELS below.
This module only computes; it never parses free text.
"""
import json
import os
import re
import numpy as np
import pandas as pd

# The only source change anywhere in this migrated copy: the original file resolved its data
# files relative to the process's CWD, which broke the moment this file moved into a backend/
# subdirectory (correctness would then depend on exactly which directory uvicorn was launched
# from). SALES_DATA_DIR is an optional env-var override; the default still finds backend/data/
# (where the real data files are symlinked from the project root) regardless of launch CWD.
_DATA_DIR = os.environ.get(
    "SALES_DATA_DIR",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "data"),
)
DATA_PATH = os.path.join(_DATA_DIR, "medical_sales_5yr_250k.csv")
# A champion is still just "least-bad of 6 options" -- nothing before this stopped a value
# whose best-available model was itself measured to be badly wrong from answering with
# "confidence: high" anyway. Found live in champions_dimensional.json (Medical Product 0068,
# 81.2% MAPE, already answering questions before this floor existed) and pervasively at week
# grain for products (79.4% average champion MAPE, several individual champions over 100%,
# one over 300%). Applies to every dimensional lookup (week/month/year) -- not the 6
# whole-business slots, which have never shown this problem and are reviewed by hand, not
# swept over 302 values at a time.
DIMENSIONAL_MAX_RELIABLE_ERROR_PCT = 40


REASONS = {
    "naive_last_value": "repeats the last known value",
    "moving_avg": "averages the recent months/weeks",
    "linear_trend": "extrapolates the straight-line trend through 2021-2024",
    "seasonal_naive": "repeats the same period from one year back",
    "chronos": "Chronos-2, a pretrained forecasting model, run on the full 2021-2024 history",
    "claude-haiku-4-5": "Claude Haiku 4.5, given the full numeric history directly and asked "
                         "to predict the next value(s) -- only used where it won a real "
                         "backtest, the same rule every other candidate had to clear",
}

METRIC_COLUMNS = {"net_sales": "net_sales", "gross_sales": "gross_sales",
                   "quantity": "quantity", "profit": "profit"}
METRIC_LABELS = {"net_sales": "net sales", "gross_sales": "gross sales",
                  "quantity": "units sold", "profit": "profit"}

DIMENSION_COLUMNS = {"branch": "stock_branch", "route": "route", "category": "category",
                      "product_type": "product_type", "customer_type": "customer_type",
                      "product": "product", "supplier": "supplier", "customer": "customer_id"}
# Which dimensions have ANY validated backtest behind them (score_dimensional.py).
# Decided by eda_medical.py's density check, not assumed -- this data is far richer than the
# old BizWiz set (250K rows vs 6,885), so scope is meaningfully wider than the old "branch +
# route only": branch/route/category/product_type/customer_type/supplier all cleared a
# comfortable density bar, and product is included too (tested despite thinner density,
# scored honestly like everything else rather than excluded by assumption). customer stays
# excluded -- individual customers are too thin (~8 rows/month, min 1) to forecast at all,
# confirmed by the density check rather than assumed the way it was last time.
DIMENSIONS_WITH_BACKTEST = {"branch", "route", "category", "product_type", "customer_type",
                             "supplier", "product"}

ALL_MODELS = ["naive_last_value", "moving_avg", "linear_trend", "seasonal_naive", "chronos"]

# Playground-only metric set -- deliberately wider than METRIC_COLUMNS (adds discount_amount,
# and a derived "cost" = quantity * unit_cost) and deliberately NOT merged into METRIC_COLUMNS,
# because METRIC_COLUMNS staying exactly the set score_whole_business.py actually backtested is what makes
# answer_question()'s "unvalidated_metric" refusal meaningful. The playground bypasses that
# refusal on purpose (see run_playground_forecast) -- these extra metrics must never leak into
# the validated Q&A path.
PLAYGROUND_METRIC_COLUMNS = {"net_sales": "net_sales", "gross_sales": "gross_sales",
                              "quantity": "quantity", "profit": "profit",
                              "discount_amount": "discount_amount"}
PLAYGROUND_METRIC_LABELS = {"net_sales": "net sales", "gross_sales": "gross sales",
                             "quantity": "units sold", "profit": "profit",
                             "discount_amount": "discount given",
                             "cost": "cost of goods (qty × unit cost)"}
MAX_PLAYGROUND_PERIODS_AHEAD = 120  # ~10 years -- generous for stress-testing, bounded so a
                                     # malformed/extreme request can't hang the page indefinitely


def _load_champions():
    """CHAMPIONS[metric][horizon] -> {model, reason}. Only metrics that were
    actually backtested (score_whole_business.py's METRICS list) appear here at all --
    that absence, not a hardcoded "!= net_sales" check, is what makes
    answer_question() refuse an unvalidated metric now."""
    with open(os.path.join(_DATA_DIR, "champions_medical.json")) as f:
        data = json.load(f)
    all_champions, all_results = data["champions"], data["results"]
    out = {}
    for metric, champions in all_champions.items():
        out[metric] = {}
        results = all_results[metric]
        for horizon, model in champions.items():
            if horizon == "year":
                error_pct = abs(results["year"][model]["diff_pct"])
                score = f"{results['year'][model]['diff_pct']:+.1f}% vs. actual"
            else:
                error_pct = results[horizon][model]["mape"]
                score = f"{error_pct:.1f}% MAPE"
            out[metric][horizon] = {
                "model": model,
                "error_pct": round(error_pct, 1),
                "reason": f"{REASONS[model]} — won the {metric}/{horizon}-level "
                          f"2021-2024→2025 backtest ({score}).",
            }
    return out


def _load_dimensional_champions():
    """DIMENSIONAL_CHAMPIONS[dimension][value] -> {model, reason}, from
    score_dimensional.py's backtest (net_sales, monthly grain, across every dimension that
    cleared eda_medical.py's density check). A (dimension, value) pair NOT in here has no
    validated forecast -- that absence is what answer_question() checks, not a hardcoded
    dimension list."""
    try:
        with open(os.path.join(_DATA_DIR, "champions_dimensional.json")) as f:
            data = json.load(f)
    except FileNotFoundError:
        return {}
    out = {}
    for dimension, values in data.items():
        out[dimension] = {}
        for value, info in values.items():
            model = info["champion"]
            score = info["scores"][model]
            out[dimension][value] = {
                "model": model, "error_pct": score,
                "reason": f"{REASONS[model]} — won the {dimension}={value} monthly "
                          f"2021-2024→2025 backtest ({score}% MAPE).",
            }
    return out


def _load_dimensional_yearly_champions():
    """DIMENSIONAL_YEARLY_CHAMPIONS[dimension][value] -> {model, reason}, from
    score_dimensional_yearly.py's backtest -- same values as DIMENSIONAL_CHAMPIONS, but scored
    on the FULL YEAR total (sum 12 predicted months, compare to the real 2025 year total)
    rather than month-to-month error. A value can have a different champion here than in
    DIMENSIONAL_CHAMPIONS -- being accurate month-to-month and being accurate on the annual
    total are different questions. A (dimension, value) pair NOT in here has no validated
    YEAR-level forecast -- answer_question() falls back to the existing next-month-only
    refusal for it. Optional file: returns {} until score_dimensional_yearly.py has been run."""
    try:
        with open(os.path.join(_DATA_DIR, "champions_dimensional_yearly.json")) as f:
            data = json.load(f)
    except FileNotFoundError:
        return {}
    out = {}
    for dimension, values in data.items():
        out[dimension] = {}
        for value, info in values.items():
            model = info["champion"]
            diff = info["diff_pct"][model]
            out[dimension][value] = {
                "model": model, "error_pct": abs(diff),
                "reason": f"{REASONS[model]} — won the {dimension}={value} full-year "
                          f"2021-2024→2025 backtest ({diff:+.1f}% vs. actual).",
            }
    return out


def _load_dimension_values():
    """Real branch/route/category/product_type/customer_type/supplier/product names from the
    data -- fed to the LLM (parse_query) as the ground truth to match a question's text
    against, and used here to verify its answer isn't hallucinated. Pulled live from the CSV
    every call -- if a branch is added tomorrow, this picks it up automatically, nothing to
    hand-maintain. "customer" is deliberately absent (500 IDs, not names -- excluded from
    backtesting by the density check, and wouldn't be a meaningful list to match text
    against even if it weren't)."""
    df = pd.read_csv(DATA_PATH)
    return {
        "branch": sorted(df["stock_branch"].unique().tolist()),
        "route": sorted(df["route"].unique().tolist()),
        "category": sorted(df["category"].unique().tolist()),
        "product_type": sorted(df["product_type"].unique().tolist()),
        "customer_type": sorted(df["customer_type"].unique().tolist()),
        "supplier": sorted(df["supplier"].unique().tolist()),
        "product": sorted(df["product"].unique().tolist()),
    }


def _load_full_backtest_scores():
    """Every candidate's real backtest MAPE, not just the champion's -- the same
    champions_medical.json/champions_dimensional.json files already have every model's score
    (score_whole_business.py's "results", score_dimensional.py's "scores"), just not surfaced
    by _load_champions() above. Used by historical_mape() to give the Model Playground
    something real to compare a fresh prediction against, without recomputing anything."""
    with open(os.path.join(_DATA_DIR, "champions_medical.json")) as f:
        whole = json.load(f)["results"]
    try:
        with open(os.path.join(_DATA_DIR, "champions_dimensional.json")) as f:
            dimensional = json.load(f)
    except FileNotFoundError:
        dimensional = {}
    return whole, dimensional


def _load_raw_scores(filename):
    """The untransformed contents of one champions_dimensional_*.json -- every candidate's
    score for every value, exactly as the score_*.py script persisted it. The champion loaders
    above reduce these files to just the winner; this keeps the whole comparison table, which
    is what a "how did every model do" view needs. Optional file -> {}."""
    try:
        with open(os.path.join(_DATA_DIR, filename)) as f:
            return json.load(f)
    except FileNotFoundError:
        return {}


def historical_mape(metric, freq, model_name, dimension=None, dimension_value=None):
    """The real MAPE score_whole_business.py/score_dimensional.py measured for this exact
    metric/dimension/model/horizon, or None if that combination was never backtested at all
    (an unvalidated metric like "cost", or a dimension/value score_dimensional.py skipped).
    Only week/month horizons are covered -- the Playground doesn't expose a "year" grain, and
    the saved year-level number is a different statistic (% diff on a full-year total, not a
    mean of per-period errors), not directly comparable to a MAPE."""
    if dimension and dimension_value:
        scores = FULL_RESULTS_DIMENSIONAL.get(dimension, {}).get(dimension_value, {}).get("scores", {})
        return scores.get(model_name)
    horizon = "week" if freq == "W" else "month"
    return FULL_RESULTS_WHOLE.get(metric, {}).get(horizon, {}).get(model_name, {}).get("mape")


CHAMPIONS = _load_champions()
DIMENSIONAL_CHAMPIONS = _load_dimensional_champions()
DIMENSIONAL_YEARLY_CHAMPIONS = _load_dimensional_yearly_champions()

def _load_dimensional_weekly_champions():
    """DIMENSIONAL_WEEKLY_CHAMPIONS[dimension][value] -> {model, reason}, from
    score_dimensional_weekly.py's backtest -- a SEPARATE, stricter-threshold population than
    DIMENSIONAL_CHAMPIONS (52 weeks of real test data required, vs 12 months), so a value can
    have a month/year champion but no week champion. Optional file: returns {} until
    score_dimensional_weekly.py has been run."""
    try:
        with open(os.path.join(_DATA_DIR, "champions_dimensional_weekly.json")) as f:
            data = json.load(f)
    except FileNotFoundError:
        return {}
    out = {}
    for dimension, values in data.items():
        out[dimension] = {}
        for value, info in values.items():
            model = info["champion"]
            score = info["scores"][model]
            out[dimension][value] = {
                "model": model, "error_pct": score,
                "reason": f"{REASONS[model]} — won the {dimension}={value} weekly "
                          f"2021-2024→2025 backtest ({score}% MAPE).",
            }
    return out


DIMENSIONAL_WEEKLY_CHAMPIONS = _load_dimensional_weekly_champions()
DIMENSION_VALUES = _load_dimension_values()
FULL_RESULTS_WHOLE, FULL_RESULTS_DIMENSIONAL = _load_full_backtest_scores()

# Raw, every-candidate score tables for the two grains the champion loaders above reduce to a
# single winner. FULL_RESULTS_DIMENSIONAL already covers monthly; these complete the set so a
# model-comparison view can show all six candidates at all three grains without re-running
# anything. Monthly/weekly entries are {champion, scores{model: mape}}; yearly entries are
# {champion, actual, predicted{model}, diff_pct{model}} -- a different statistic, kept distinct
# rather than flattened into a fake MAPE.
RAW_SCORES_WEEKLY = _load_raw_scores("champions_dimensional_weekly.json")
RAW_SCORES_YEARLY = _load_raw_scores("champions_dimensional_yearly.json")

# (column name, display label, one-line description, which group it belongs to) for every
# column in the raw CSV -- feeds the "Data & History" page's column reference. Order here is
# the display order within each group, not the CSV's column order.
_COLUMN_DOCS = [
    ("sales_id", "Sale ID", "Unique identifier for this transaction line", "Transaction"),
    ("sales_date", "Date", "Calendar date the sale was recorded", "Transaction"),
    ("sales_status", "Status", "Completed, Cancelled or Returned", "Transaction"),
    ("product_id", "Product ID", "Internal SKU code", "Product & Supplier"),
    ("product", "Product", "Product name", "Product & Supplier"),
    ("category", "Category", "Therapeutic / product category", "Product & Supplier"),
    ("product_type", "Product Type", "Broad classification, e.g. Tablet, Surgical Supply", "Product & Supplier"),
    ("supplier_id", "Supplier ID", "Internal supplier code", "Product & Supplier"),
    ("supplier", "Supplier", "Supplier name", "Product & Supplier"),
    ("customer_id", "Customer ID", "Anonymized customer identifier", "Customer"),
    ("customer_type", "Customer Type", "Channel the customer belongs to, e.g. Clinic, Hospital", "Customer"),
    ("branch_id", "Branch ID", "Internal branch code", "Location"),
    ("stock_branch", "Branch", "Selling / stocking branch", "Location"),
    ("route_id", "Route ID", "Internal delivery route code", "Location"),
    ("route", "Route", "Delivery route", "Location"),
    ("quantity", "Quantity", "Units sold in this transaction", "Commercial & Inventory"),
    ("unit_price", "Unit Price", "List price per unit", "Commercial & Inventory"),
    ("offer", "Offer", "Whether a promotional offer applied", "Commercial & Inventory"),
    ("discount_pct", "Discount %", "Discount percentage applied", "Commercial & Inventory"),
    ("gross_sales", "Gross Sales", "Revenue before discount", "Commercial & Inventory"),
    ("discount_amount", "Discount Amount", "Value discounted off gross sales", "Commercial & Inventory"),
    ("net_sales", "Net Sales", "Revenue after discount -- the primary sales metric", "Commercial & Inventory"),
    ("unit_cost", "Unit Cost", "Cost per unit to the business", "Commercial & Inventory"),
    ("profit", "Profit", "Net sales minus cost of goods", "Commercial & Inventory"),
    ("payment_method", "Payment Method", "How the customer paid", "Commercial & Inventory"),
    ("inventory_before", "Stock Before", "Inventory level before this sale", "Commercial & Inventory"),
    ("inventory_after", "Stock After", "Inventory level after this sale", "Commercial & Inventory"),
]


def _load_dataset_overview():
    """Real, computed summary of the raw dataset for the "Data & History" page -- row count,
    date span, every column with a plain-language label, and a distinct-value count for every
    dimension. Nothing here is hand-typed: change the CSV and this changes with it, same
    discipline as DIMENSION_VALUES above."""
    df = pd.read_csv(DATA_PATH, parse_dates=["sales_date"])
    date_start, date_end = df["sales_date"].min(), df["sales_date"].max()
    return {
        "total_rows": len(df),
        "total_columns": len(df.columns),
        "date_start": date_start.date().isoformat(),
        "date_end": date_end.date().isoformat(),
        "years_covered": date_end.year - date_start.year + 1,
        "columns": [
            {"name": name, "label": label, "description": desc, "group": group}
            for name, label, desc, group in _COLUMN_DOCS
        ],
        "counts": {
            "branch": int(df["stock_branch"].nunique()),
            "route": int(df["route"].nunique()),
            "category": int(df["category"].nunique()),
            "product_type": int(df["product_type"].nunique()),
            "product": int(df["product"].nunique()),
            "supplier": int(df["supplier"].nunique()),
            "customer_type": int(df["customer_type"].nunique()),
            "customer": int(df["customer_id"].nunique()),
        },
        "categorical_fields": {
            "payment_method": sorted(df["payment_method"].unique().tolist()),
            "sales_status": sorted(df["sales_status"].unique().tolist()),
            "offer": sorted(df["offer"].unique().tolist()),
        },
        "total_net_sales": float(df["net_sales"].sum()),
    }


DATASET_OVERVIEW = _load_dataset_overview()


def _load_display_names():
    """Client-facing display names for branch/route/supplier/product -- cosmetic only, generated
    once (see gen_display_names.py at the repo root) and checked into data/display_names.json. The model,
    every API filter and every backtest still key on the real values in the CSV; this dict is
    consulted ONLY when rendering something to a person. Never used for matching or computation."""
    try:
        with open(os.path.join(_DATA_DIR, "display_names.json")) as f:
            return json.load(f)
    except FileNotFoundError:
        return {}


DISPLAY_NAMES = _load_display_names()


def _build_reverse_name_patterns():
    """(compiled regex, real_name) for every display name, longest-phrase-first so e.g.
    "Quebec City Branch" is tried before any shorter name that might otherwise partially
    overlap it. Word-boundary anchored and case-insensitive, so this only replaces a genuine
    whole mention of the display name, never a fragment of an unrelated word."""
    pairs = [(display, real) for dim_map in DISPLAY_NAMES.values() for real, display in dim_map.items()]
    pairs.sort(key=lambda p: len(p[0]), reverse=True)
    return [(re.compile(r"\b" + re.escape(display) + r"\b", re.IGNORECASE), real) for display, real in pairs]


_REVERSE_NAME_PATTERNS = _build_reverse_name_patterns()


def _build_forward_name_patterns():
    """(compiled regex, display_name) for every REAL value -- the inverse of
    _REVERSE_NAME_PATTERNS, for scrubbing real identifiers back OUT of generated text (LLM
    narration, a champion's "reason" string) before it reaches a client. Same longest-first,
    word-boundary-anchored construction, for the same reason."""
    pairs = [(real, display) for dim_map in DISPLAY_NAMES.values() for real, display in dim_map.items()]
    pairs.sort(key=lambda p: len(p[0]), reverse=True)
    return [(re.compile(r"\b" + re.escape(real) + r"\b"), display) for real, display in pairs]


_FORWARD_NAME_PATTERNS = _build_forward_name_patterns()


def apply_display_names(text):
    """The inverse of resolve_display_names: swap real identifiers ("Medical Branch 02") for
    their client-facing display name ("Vancouver Branch") in text that's about to be shown to a
    user -- LLM narration and a champion's "reason" string are grounded in the real data, so
    they say the real name unless this runs. Every number and claim in the text is untouched;
    this only ever rewrites a name, never a figure."""
    if text is None:
        return text
    for pattern, display in _FORWARD_NAME_PATTERNS:
        text = pattern.sub(display, text)
    return text


def resolve_display_names(text):
    """If free-text (a typed or clicked Ask-AI question) mentions a client-facing display name
    -- "Vancouver Branch" -- swap in the real underlying value ("Medical Branch 02") before this
    reaches parse_query/parse_intent. Those still match against the real DIMENSION_VALUES
    vocabulary, so a question phrased the way the UI now looks needs this translation to
    resolve at all. Only used for the copy handed to the parser -- what's logged and narrated
    back to the user stays exactly what they typed."""
    for pattern, real in _REVERSE_NAME_PATTERNS:
        text = pattern.sub(real, text)
    return text


def _build_display_export_csv():
    """A byte-for-byte copy of the real dataset with stock_branch/route/supplier/product
    replaced by their display names -- so the file a client downloads matches what the app
    shows them. Built once at import time (same pattern as DATASET_OVERVIEW) since the source
    CSV doesn't change at runtime."""
    df = pd.read_csv(DATA_PATH)
    rename_cols = {"stock_branch": "branch", "route": "route", "supplier": "supplier", "product": "product"}
    for col, dim in rename_cols.items():
        mapping = DISPLAY_NAMES.get(dim, {})
        if mapping:
            df[col] = df[col].map(mapping).fillna(df[col])
    return df.to_csv(index=False).encode("utf-8")


DISPLAY_EXPORT_CSV = _build_display_export_csv()


def load_series(freq="MS", metric="net_sales", dimension=None, dimension_value=None):
    column = METRIC_COLUMNS.get(metric, "net_sales")
    df = pd.read_csv(DATA_PATH, parse_dates=["sales_date"])
    if dimension and dimension_value:
        df = df[df[DIMENSION_COLUMNS[dimension]] == dimension_value]
    s = df.set_index("sales_date").resample(freq)[column].sum()
    if dimension and dimension_value and len(s):
        # A specific branch/route can have a genuinely zero-activity month --
        # reindex so the series stays continuous instead of silently skipping it.
        full_index = pd.date_range(s.index.min(), s.index.max(), freq=freq)
        s = s.reindex(full_index, fill_value=0.0)
    return s.iloc[1:-1] if freq == "W" else s  # trim partial edge weeks only


def load_playground_series(freq, metric, dimension=None, dimension_value=None):
    """Same shape as load_series(), but against PLAYGROUND_METRIC_COLUMNS' wider set --
    kept as its own function rather than widening load_series() itself, so the validated
    Q&A path can never accidentally reach a metric it never backtested."""
    df = pd.read_csv(DATA_PATH, parse_dates=["sales_date"])
    if dimension and dimension_value:
        df = df[df[DIMENSION_COLUMNS[dimension]] == dimension_value]
    if metric == "cost":
        df = df.assign(_pg_metric=df["quantity"] * df["unit_cost"])
        column = "_pg_metric"
    else:
        column = PLAYGROUND_METRIC_COLUMNS.get(metric, "net_sales")
    s = df.set_index("sales_date").resample(freq)[column].sum()
    if dimension and dimension_value and len(s):
        full_index = pd.date_range(s.index.min(), s.index.max(), freq=freq)
        s = s.reindex(full_index, fill_value=0.0)
    return s.iloc[1:-1] if freq == "W" else s


def resample_yearly(series):
    """Collapse a monthly series into yearly sums, keeping only years with all 12 months
    present -- an incomplete year's partial sum would sit on the same axis as a real year at a
    fraction of the value, which is its own kind of misleading chart. Any chart whose final
    point is a full-year total (a year-horizon forecast, a year-only backtest's held-back
    actual) must plot history in the SAME unit -- year totals, not raw monthly points -- or the
    single year-scale point reads as a 10x+ spike off a flat monthly line. Shared by every such
    chart path (dashboard trend, ask/playground history) so this is computed one way, not
    reimplemented per caller."""
    yearly = series.resample("YS").sum()
    counts = series.resample("YS").size()
    return yearly[counts == 12]


def run_playground_forecast(metric, dimension, dimension_value, target_year=None,
                             target_month=None, periods_ahead=None, freq="MS", log_fn=None):
    """Direct model-testing tool -- deliberately bypasses the validation gate
    answer_question() enforces. Runs every candidate in ALL_MODELS on ANY metric/dimension
    combination, including ones never backtested, and can push a forecast further out than
    Phase 1's normal "next month only" limit. The point is to see raw numbers for
    combinations that haven't been proven yet, or to stress a validated one past its normal
    scope -- clearly separate from the "only show what's actually been proven" guarantee the
    main Q&A path keeps.

    Every malformed-input problem (bad dimension_value, multiple/non-numeric year, a target
    too far out, not enough history) comes back as {"error": "..."} rather than raising --
    the caller shows that string directly rather than crashing. A per-candidate forecast
    failure (e.g. a model needing more history than is available) lands in the "failures"
    dict instead of aborting the other candidates.

    If the resolved target period is already inside the recorded data, this runs a genuine
    ad-hoc backtest instead of refusing: each candidate trains ONLY on data strictly before
    that period, and the result includes the real recorded value alongside every prediction,
    so a past period can be used to see how each model would actually have done.

    Returns "log": a step-by-step trace of what actually ran -- the same treatment
    answer_question() already gives its own path. These are real emitted steps (resolved
    target, train/test split, each model's own input window and raw output, each model's
    score), not a narrated summary written after the fact.
    """
    steps = []
    _outer_log_fn = log_fn

    def _tee(msg):  # accumulate for the caller AND still honour any log_fn passed in
        steps.append(msg)
        if _outer_log_fn:
            _outer_log_fn(msg)

    log_fn = _tee

    if dimension:
        if dimension not in (set(DIMENSION_VALUES) | {"customer"}):
            return {"error": f"{dimension!r} isn't a real dimension type."}
        real_values = DIMENSION_VALUES.get(dimension, [])
        normalized = str(dimension_value or "").strip()
        if not normalized:
            return {"error": f"Pick a specific {dimension} -- leave the value blank only when "
                              f"dimension is 'Whole business'.",
                    "valid_values": real_values}
        if not real_values:
            return {"error": f"No {dimension} list is loaded to match against yet -- "
                              f"nothing typed here can be verified."}
        match = next((v for v in real_values if v.casefold() == normalized.casefold()), None)
        if not match:
            return {"error": f"{dimension_value!r} isn't a real {dimension} -- no match "
                              f"(case-insensitive) in the data.",
                    "valid_values": real_values}
        dimension_value = match  # normalized to the real, correctly-cased value
    else:
        dimension_value = None

    if metric not in PLAYGROUND_METRIC_COLUMNS and metric != "cost":
        return {"error": f"{metric!r} isn't a real metric/column."}

    # An explicit year/month always resolves at monthly grain -- Phase 1's own dimensional
    # champions are monthly-only, and "which week of that month" has no single answer anyway.
    if target_year is not None or target_month is not None:
        freq = "MS"

    full_series = load_playground_series(freq, metric, dimension, dimension_value)
    log_fn(f"playground: loaded {len(full_series)} points for metric={metric!r} "
           f"dimension={dimension!r} value={dimension_value!r} freq={freq!r}")
    if len(full_series) < 2:
        return {"error": f"Only {len(full_series)} data point(s) exist for this combination -- "
                          f"not enough history to forecast anything."}
    last_date = full_series.index.max()
    offset = pd.DateOffset(weeks=1) if freq == "W" else pd.DateOffset(months=1)

    def _periods_between(start, end):
        # A DateOffset has no fixed length (a month isn't a constant number of days), so a
        # Timedelta can't be divided by one -- count in calendar units instead, same pattern
        # answer_question() already uses for months_ahead/years_ahead above.
        if freq == "W":
            return int(round((end - start).days / 7))
        return (end.year - start.year) * 12 + (end.month - start.month)

    is_backtest, actual_value = False, None
    year_only = False
    if target_year is not None or target_month is not None:
        year_only = target_month is None
        if not year_only:
            year = target_year or (last_date.year if target_month <= last_date.month else last_date.year + 1)
            target_period = pd.Timestamp(year=year, month=target_month, day=1)
        else:
            target_period = pd.Timestamp(year=target_year, month=12, day=1)  # year-only -> December of that year

        if target_period <= last_date:
            is_backtest = True
            # Year-only means "the full year," same as everywhere else in this app -- train on
            # everything through the END OF THE PRIOR YEAR and forecast all 12 months, so the
            # backtest compares a genuine 12-month path, not just December's single value. A
            # specific month stays a single-point target (train through 1 period before it).
            train_end = pd.Timestamp(year=target_year - 1, month=12, day=1) if year_only else target_period - offset
            train_series = full_series.loc[:train_end]
            if year_only:
                # "actual" for a full-year target is the year's total, not December's single
                # month -- matches how answer_question()'s year branch and
                # score_whole_business.py's year-level backtest both already define it.
                year_actuals = full_series.loc[pd.Timestamp(year=target_year, month=1, day=1):target_period]
                actual_value = float(year_actuals.sum()) if len(year_actuals) == 12 else None
            elif target_period in full_series.index:
                actual_value = float(full_series.loc[target_period])
            if len(train_series) < 2:
                return {"error": f"Only {len(train_series)} point(s) of history exist before "
                                  f"{train_end.strftime('%b %Y')} -- too early to have "
                                  f"trained anything on yet."}
            periods_ahead = _periods_between(train_series.index.max(), target_period)
        else:
            train_series = full_series
            periods_ahead = _periods_between(last_date, target_period)
    else:
        train_series = full_series
        periods_ahead = periods_ahead or 1
        target_period = last_date + offset * periods_ahead

    if periods_ahead < 1:
        return {"error": "That period is already fully covered by the training data used -- "
                          "pick something further ahead to actually test a forecast."}
    if periods_ahead > MAX_PLAYGROUND_PERIODS_AHEAD:
        return {"error": f"{periods_ahead} periods ahead is too far for this tool (capped at "
                          f"{MAX_PLAYGROUND_PERIODS_AHEAD}) -- pick something closer."}

    grain_word = "week" if freq == "W" else ("year" if year_only else "month")
    log_fn(f"resolved target: {target_period.strftime('%b %Y')} "
           f"({periods_ahead} {grain_word}(s) ahead, grain={grain_word})")
    if is_backtest:
        log_fn(f"target is inside recorded data -> running a REAL backtest: every candidate "
               f"trains only on {train_series.index.min().strftime('%b %Y')}"
               f"..{train_series.index.max().strftime('%b %Y')} "
               f"({len(train_series)} points), nothing at or after the target")
        if actual_value is not None:
            log_fn(f"held-back actual for scoring: {actual_value:,.1f}")
    else:
        log_fn(f"target is beyond recorded data -> a true forward forecast, no actual to "
               f"score against (history ends {train_series.index.max().strftime('%b %Y')})")
    log_fn(f"running {len(ALL_MODELS)} candidates: {', '.join(ALL_MODELS)}")

    # Full actual path for the backtest case -- lets MAPE below be computed across every
    # period_ahead step, not just the final one, when more than one period was requested.
    actual_path = None
    if is_backtest:
        actual_path = full_series.loc[train_series.index.max() + offset:target_period].values

    def _mape(actual_arr, pred_arr):
        actual_arr, pred_arr = np.asarray(actual_arr, dtype=float), np.asarray(pred_arr, dtype=float)
        if np.any(actual_arr == 0):  # avoid div-by-zero -- same fallback already used in score_dimensional.py
            return float(np.mean(np.abs(actual_arr - pred_arr)) / (np.mean(np.abs(actual_arr)) + 1e-9) * 100)
        return float(np.mean(np.abs((actual_arr - pred_arr) / actual_arr)) * 100)

    predictions, failures = {}, {}
    for name in ALL_MODELS:
        try:
            pred = run_forecast(name, train_series, periods_ahead, freq, log_fn=log_fn,
                                 metric_label=METRIC_LABELS.get(metric, metric),
                                 dimension=dimension, dimension_value=dimension_value)
            if year_only:
                # The headline number for a full-year target is the year's total, not
                # December's single month -- same reasoning as actual_value above. MAPE
                # becomes "% off on the annual total" (score_whole_business.py's own
                # year-level statistic), not a mean of 12 separate monthly errors, which
                # can look worse than the total actually is when over/under months offset.
                value = float(np.sum(pred[-12:]))
                live_mape = (abs((actual_value - value) / actual_value) * 100
                             if actual_value else None)
            else:
                value = float(pred[-1])
                live_mape = (_mape(actual_path, pred)
                             if actual_path is not None and len(actual_path) == len(pred) else None)
            hist = historical_mape(metric, freq, name, dimension, dimension_value)
            predictions[name] = {
                "value": value,
                "live_mape": live_mape,
                "historical_mape": hist,
            }
            log_fn(f"{name}: predicted {value:,.1f}"
                   + (f" | this test: {live_mape:.1f}% error" if live_mape is not None else "")
                   + (f" | its offline backtest: {hist:.1f}% MAPE" if hist is not None
                       else " | never backtested for this exact combination"))
        except Exception as e:
            log_fn(f"playground: {name} failed -- {type(e).__name__}: {e}")
            failures[name] = f"{type(e).__name__}: {e}"

    scored = {n: p["live_mape"] for n, p in predictions.items() if p["live_mape"] is not None}
    if scored:
        best = min(scored, key=scored.get)
        log_fn(f"ranked on THIS test: "
               + ", ".join(f"{n} {scored[n]:.1f}%" for n in sorted(scored, key=scored.get))
               + f"  ->  best here: {best}")
    else:
        log_fn("no actual exists for this target, so nothing can be scored on this run -- "
               "the offline backtest MAPE column is the only real accuracy evidence here")

    # Claude's historical (already-computed offline) MAPE for this exact selection -- read-only
    # informational context for the client-facing Model Performance view, NOT a live run: this
    # never calls run_forecast("claude-haiku-4-5", ...), same cost/validation-purity rule as
    # ALL_MODELS excluding it above. None whenever there's nothing real to show (year_only, or
    # this exact metric/dimension/value/horizon was never backtested) -- never a guess.
    claude_historical_mape = None if year_only else historical_mape(
        metric, freq, "claude-haiku-4-5", dimension, dimension_value)

    return {
        "error": None, "metric": metric, "dimension": dimension, "dimension_value": dimension_value,
        "history": train_series, "target_period": target_period, "periods_ahead": periods_ahead,
        "freq": freq, "is_backtest": is_backtest, "actual_value": actual_value, "year_only": year_only,
        "predictions": predictions, "failures": failures,
        "claude_historical_mape": claude_historical_mape, "log": steps,
    }


def _emit(log_fn, msg):
    (log_fn or (lambda m: print(f"[model] {m}")))(msg)


_CHRONOS_PIPELINE = None


def _get_chronos_pipeline():
    """Chronos2Pipeline.from_pretrained() re-checks the model with HuggingFace Hub on every
    call (visible as the "unauthenticated requests" warning) -- normally a quick cache-hit, but
    genuinely at the mercy of that network round-trip, which has been observed taking anywhere
    from under a second to several minutes. The actual model weights never change between
    calls in one process, so loading it once and reusing the same pipeline object removes that
    variance entirely instead of just hoping the network is fast this time."""
    global _CHRONOS_PIPELINE
    if _CHRONOS_PIPELINE is None:
        from chronos import Chronos2Pipeline
        _CHRONOS_PIPELINE = Chronos2Pipeline.from_pretrained("amazon/chronos-2")
    return _CHRONOS_PIPELINE


def run_forecast(model_name, train_series, horizon, freq="W", log_fn=None,
                  metric_label=None, dimension=None, dimension_value=None):
    """metric_label/dimension/dimension_value are only consumed by the claude-haiku-4-5
    branch -- they tell the LLM what its numbers actually measure and which slice they
    cover. The 5 local models ignore them (a least-squares fit doesn't care what the
    column is called). They're optional so the offline scoring scripts and validate_2025.py
    keep working unchanged, but every live call site passes them."""
    cycle = 52 if freq == "W" else 12
    _emit(log_fn, f"MODEL INPUT: model={model_name!r} freq={freq!r} horizon={horizon} "
                   f"history={len(train_series)} points, last 6: {list(np.round(train_series.values[-6:], 1))}")

    if model_name == "naive_last_value":
        pred = np.full(horizon, train_series.iloc[-1])
    elif model_name == "moving_avg":
        window = 8 if freq == "W" else 3
        pred = np.full(horizon, train_series.iloc[-window:].mean())
    elif model_name == "linear_trend":
        x = np.arange(len(train_series))
        slope, intercept = np.polyfit(x, train_series.values, 1)
        fx = np.arange(len(train_series), len(train_series) + horizon)
        pred = slope * fx + intercept
    elif model_name == "seasonal_naive":
        end = -cycle + horizon
        pred = train_series.iloc[-cycle:end if end < 0 else None].values[:horizon]
    elif model_name == "chronos":
        input_df = pd.DataFrame({"item_id": "business", "timestamp": train_series.index,
                                  "target": train_series.values})
        pipe = _get_chronos_pipeline()
        out = pipe.predict_df(input_df, prediction_length=horizon, freq=freq)
        pred = out["predictions"].values[:horizon]
    elif model_name == "claude-haiku-4-5":
        # The LLM candidate -- only reachable here if it actually won a real backtest for
        # this exact metric/horizon (score_whole_business.py / score_dimensional.py), same
        # rule every other candidate had to clear. Real cost per call now, unlike the 5
        # local candidates -- see llm_client.py for why this stays out of the Model
        # Playground's ALL_MODELS list (kept bounded to backtested, live-answer use only).
        from app.core.llm_client import llm_predict  # package-path adaptation, see llm_client.py's own note
        period_label = "weekly" if freq == "W" else "monthly"
        # metric_label passed through as-is, including None: llm_predict then says "the
        # series" rather than asserting a metric nobody told it about. Defaulting to
        # "net sales" here is exactly the bug this integration fixed.
        pred = np.asarray(llm_predict(
            list(train_series.values), horizon, period_label, metric_label=metric_label,
            dimension=dimension, dimension_value=dimension_value, log_fn=log_fn))
    else:
        raise ValueError(f"unknown model_name: {model_name}")

    _emit(log_fn, f"MODEL OUTPUT (raw): {list(np.round(np.asarray(pred), 1))}")
    return pred


def run_forecast_with_range(model_name, train_series, horizon, freq="W", log_fn=None,
                             metric_label=None, dimension=None, dimension_value=None):
    """Same as run_forecast, but also returns a (low, high) 80% range per step
    when the model actually produces one (Chronos-2's own quantiles) -- (None,
    None) per step otherwise. metric_label/dimension/dimension_value are forwarded
    to run_forecast for the LLM candidate's prompt; chronos's own branch ignores them."""
    _emit(log_fn, f"MODEL INPUT: model={model_name!r} freq={freq!r} horizon={horizon} "
                   f"history={len(train_series)} points, last 6: {list(np.round(train_series.values[-6:], 1))}")
    if model_name == "chronos":
        input_df = pd.DataFrame({"item_id": "business", "timestamp": train_series.index,
                                  "target": train_series.values})
        pipe = _get_chronos_pipeline()
        out = pipe.predict_df(input_df, prediction_length=horizon, freq=freq)
        pred, lo, hi = out["predictions"].values[:horizon], out["0.1"].values[:horizon], out["0.9"].values[:horizon]
        _emit(log_fn, f"MODEL OUTPUT (raw): pred={list(np.round(pred, 1))} "
                       f"lo={list(np.round(lo, 1))} hi={list(np.round(hi, 1))}")
        return pred, lo, hi
    pred = run_forecast(model_name, train_series, horizon, freq, log_fn=log_fn,
                         metric_label=metric_label, dimension=dimension,
                         dimension_value=dimension_value)
    return pred, np.full(horizon, np.nan), np.full(horizon, np.nan)


def confidence_note(years_ahead):
    if years_ahead <= 1:
        return "high", "this is the exact horizon that was backtested"
    if years_ahead <= 3:
        return "moderate", (f"this is {years_ahead} years beyond the backtested horizon -- "
                             f"extrapolated, not directly validated")
    return "low", (f"this is {years_ahead} years beyond the backtested horizon -- "
                    f"well past what's been tested; treat as a rough extrapolation, not a prediction to plan around")


def month_confidence_note(months_ahead):
    if months_ahead <= 1:
        return "high", "this is the exact horizon that was backtested"
    if months_ahead <= 6:
        return "moderate", (f"this is {months_ahead} months beyond the backtested horizon -- "
                             f"extrapolated, not directly validated")
    return "low", (f"this is {months_ahead} months beyond the backtested horizon -- "
                    f"well past what's been tested; treat as a rough extrapolation, not a prediction to plan around")


def _log(steps, msg):
    print(f"[answer_question] {msg}")
    steps.append(msg)


def answer_question(horizon, target_year=None, target_month=None, metric="net_sales",
                     dimension=None, dimension_value=None):
    """horizon in {'week','month','year'}; target_year/target_month optional;
    metric in METRIC_COLUMNS; dimension+dimension_value optional (e.g.
    ("branch", "Vaughan")) -> dict with predicted_value, model_name, reason,
    series, is_actual, period_label, out_of_range, metric, log.

    Dimension handling (Phase 1 -- see score_dimensional.py):
    - No dimension: whole-business, exactly as before.
    - Dimension + value WITH a validated backtest (currently branch/route
      only, from DIMENSIONS_WITH_BACKTEST + DIMENSIONAL_CHAMPIONS): actual
      lookups work for any period; FORECASTS are scoped to "next month" only
      for now, matching exactly what was backtested -- multi-period-ahead
      dimensional forecasting is a real future extension, not built yet.
    - Dimension + value with NO validated backtest (category/product/
      supplier/customer, or a value score_dimensional.py skipped for
      insufficient data): refused, same honest "not built yet" message as
      before -- just now driven by which dimensions actually have entries
      in DIMENSIONAL_CHAMPIONS, not a hardcoded "always refuse" rule.
    """
    steps = []
    log_fn = lambda msg: _log(steps, msg)  # noqa: E731
    metric_label = METRIC_LABELS.get(metric, metric)
    freq = "W" if horizon == "week" else "MS"

    _log(steps, f"horizon={horizon!r} target_year={target_year!r} target_month={target_month!r} "
                 f"metric={metric!r} dimension={dimension!r} dimension_value={dimension_value!r}")

    # ---------------- Dimensional path ----------------
    if dimension and dimension_value:
        has_backtest = (dimension in DIMENSIONS_WITH_BACKTEST
                         and dimension_value in DIMENSIONAL_CHAMPIONS.get(dimension, {}))
        _log(steps, f"dimension={dimension} is in Phase 1 (branch/route)? "
                     f"{dimension in DIMENSIONS_WITH_BACKTEST} | has a validated champion for "
                     f"{dimension_value!r}? {has_backtest}")

        series = load_series("MS", metric, dimension, dimension_value)  # Phase 1 = monthly only

        # Actual lookups always work, any dimension, any metric -- it's a real sum, not a model.
        if target_year is not None or target_month is not None:
            if target_month is not None:
                resolved_year = target_year or (series.index.max().year
                                                 if target_month <= series.index.max().month
                                                 else series.index.max().year + 1)
                target_period = pd.Timestamp(year=resolved_year, month=target_month, day=1)
                period_label = f"{target_period.strftime('%B %Y')} ({dimension}={dimension_value})"
            else:
                target_period = None
                period_label = f"{target_year} ({dimension}={dimension_value})"

            if target_period is not None and target_period in series.index:
                val = float(series.loc[target_period])
                _log(steps, f"{period_label} is a real recorded month -> actual {metric_label} {val:,.1f}")
                return {"predicted_value": val, "model_name": None,
                        "reason": f"Directly summed {metric_label} for {dimension}={dimension_value} "
                                  f"-- not modeled.",
                        "series": series, "is_actual": True, "period_label": period_label,
                        "out_of_range": False, "metric": metric, "log": steps}
            if target_period is None and target_year in series.index.year.values:
                val = float(series[series.index.year == target_year].sum())
                _log(steps, f"{period_label} is a real recorded year -> actual {metric_label} {val:,.1f}")
                return {"predicted_value": val, "model_name": None,
                        "reason": f"Directly summed {metric_label} for {dimension}={dimension_value} "
                                  f"-- not modeled.",
                        "series": series, "is_actual": True, "period_label": period_label,
                        "out_of_range": False, "metric": metric, "log": steps}

            # A pure year target (no specific month) with a validated YEAR-level champion for
            # this exact (dimension, value) -- score_dimensional_yearly.py's backtest, separate
            # from the month-level one above (a value can win one and not the other). Everything
            # else -- a month beyond next month, or a year with no yearly champion -- still
            # refuses exactly as before.
            yearly_champ = (target_month is None
                             and DIMENSIONAL_YEARLY_CHAMPIONS.get(dimension, {}).get(dimension_value))
            if yearly_champ:
                if yearly_champ["error_pct"] > DIMENSIONAL_MAX_RELIABLE_ERROR_PCT:
                    _log(steps, f"{dimension}={dimension_value} HAS a year champion "
                                 f"({yearly_champ['model']}) but its own backtested error "
                                 f"({yearly_champ['error_pct']:.1f}%) exceeds the "
                                 f"{DIMENSIONAL_MAX_RELIABLE_ERROR_PCT}% reliability floor -> "
                                 f"refusing rather than answering with a number already proven unreliable")
                    return {"predicted_value": None, "model_name": None, "reason": None,
                            "series": series, "is_actual": False, "period_label": period_label,
                            "out_of_range": True, "metric": metric,
                            "champion_too_unreliable": True, "log": steps}
                last_date = series.index.max()
                years_ahead = target_year - last_date.year
                model_name, reason, error_pct = yearly_champ["model"], yearly_champ["reason"], yearly_champ["error_pct"]
                months_needed = years_ahead * 12
                _log(steps, f"{dimension}={dimension_value} has a validated YEAR champion "
                             f"({model_name}) -> running it {months_needed} month(s) ahead to "
                             f"cover {target_year}")
                pred, lo, hi = run_forecast_with_range(model_name, series, months_needed, "MS",
                                                        log_fn=log_fn, metric_label=metric_label,
                                                        dimension=dimension,
                                                        dimension_value=dimension_value)
                target_months_pred = pred[-12:]
                predicted_value = float(np.sum(target_months_pred))
                range_low = float(np.nansum(lo[-12:])) if not np.all(np.isnan(lo)) else None
                range_high = float(np.nansum(hi[-12:])) if not np.all(np.isnan(hi)) else None
                level, why = confidence_note(years_ahead)
                _log(steps, f"{target_year} total for {dimension}={dimension_value}: "
                             f"{predicted_value:,.1f}  confidence={level} -- {why}")
                return {"predicted_value": predicted_value, "model_name": model_name, "error_pct": error_pct,
                        "reason": reason + f" Extrapolated {years_ahead} extra year(s) past "
                                            f"that to reach {target_year}.",
                        "series": series, "is_actual": False, "period_label": period_label,
                        "out_of_range": False, "metric": metric, "years_ahead": years_ahead,
                        "confidence_level": level, "confidence_reason": why,
                        "range_low": range_low, "range_high": range_high, "log": steps}

            _log(steps, f"{period_label} isn't a recorded period, and dimensional forecasting "
                         f"beyond 'next month' isn't built yet -> refusing")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": period_label,
                    "out_of_range": True, "metric": metric,
                    "dimension_forecast_out_of_range": True, "log": steps}

        if not has_backtest or metric != "net_sales":
            _log(steps, f"no validated forecast for {dimension}={dimension_value!r}, metric={metric!r} -> refusing")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": None,
                    "out_of_range": True, "metric": metric,
                    "unvalidated_dimension": True, "log": steps}

        if horizon == "week":
            # A fully separate validation axis from the month/year champions below -- many
            # values (especially individual products) that clear the monthly bar don't clear
            # weekly's stricter one (52 real weeks vs 12 months). Absence here is an honest
            # refusal, never a silent substitution of the monthly champion for a week question
            # -- that silent substitution is exactly what this branch replaces (previously
            # "next week" for a dimension quietly answered with a monthly forecast).
            weekly_champ = DIMENSIONAL_WEEKLY_CHAMPIONS.get(dimension, {}).get(dimension_value)
            if not weekly_champ:
                _log(steps, f"no validated WEEK-level forecast for {dimension}={dimension_value!r} -> refusing")
                return {"predicted_value": None, "model_name": None, "reason": None,
                        "series": series, "is_actual": False, "period_label": None,
                        "out_of_range": True, "metric": metric,
                        "unvalidated_dimension": True, "log": steps}
            if weekly_champ["error_pct"] > DIMENSIONAL_MAX_RELIABLE_ERROR_PCT:
                _log(steps, f"{dimension}={dimension_value} HAS a week champion "
                             f"({weekly_champ['model']}) but its own backtested error "
                             f"({weekly_champ['error_pct']:.1f}%) exceeds the "
                             f"{DIMENSIONAL_MAX_RELIABLE_ERROR_PCT}% reliability floor -> "
                             f"refusing rather than answering with a number already proven unreliable")
                return {"predicted_value": None, "model_name": None, "reason": None,
                        "series": series, "is_actual": False, "period_label": None,
                        "out_of_range": True, "metric": metric,
                        "champion_too_unreliable": True, "log": steps}
            weekly_series = load_series("W", metric, dimension, dimension_value)
            model_name, reason, error_pct = weekly_champ["model"], weekly_champ["reason"], weekly_champ["error_pct"]
            pred = run_forecast(model_name, weekly_series, 1, "W", log_fn=log_fn,
                                 metric_label=metric_label, dimension=dimension,
                                 dimension_value=dimension_value)
            predicted_value = float(pred[0])
            period_label = ("week of " + (weekly_series.index.max() + pd.Timedelta(weeks=1)).strftime("%b %d, %Y")
                             + f" ({dimension}={dimension_value})")
            _log(steps, f"-> {period_label}: {predicted_value:,.1f}")
            return {"predicted_value": predicted_value, "model_name": model_name, "reason": reason,
                    "error_pct": error_pct,
                    "series": weekly_series, "is_actual": False, "period_label": period_label,
                    "out_of_range": False, "metric": metric, "weeks_ahead": 1,
                    "confidence_level": "high", "confidence_reason": "this is the exact horizon that was backtested",
                    "range_low": None, "range_high": None, "log": steps}

        champ = DIMENSIONAL_CHAMPIONS[dimension][dimension_value]
        if champ["error_pct"] > DIMENSIONAL_MAX_RELIABLE_ERROR_PCT:
            _log(steps, f"{dimension}={dimension_value} HAS a month champion "
                         f"({champ['model']}) but its own backtested error "
                         f"({champ['error_pct']:.1f}%) exceeds the "
                         f"{DIMENSIONAL_MAX_RELIABLE_ERROR_PCT}% reliability floor -> "
                         f"refusing rather than answering with a number already proven unreliable")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": None,
                    "out_of_range": True, "metric": metric,
                    "champion_too_unreliable": True, "log": steps}
        model_name, reason, error_pct = champ["model"], champ["reason"], champ["error_pct"]
        pred = run_forecast(model_name, series, 1, "MS", log_fn=log_fn,
                             metric_label=metric_label, dimension=dimension,
                             dimension_value=dimension_value)
        predicted_value = float(pred[0])
        period_label = f"{(series.index.max() + pd.DateOffset(months=1)).strftime('%B %Y')} ({dimension}={dimension_value})"
        _log(steps, f"-> {period_label}: {predicted_value:,.1f}")
        return {"predicted_value": predicted_value, "model_name": model_name, "reason": reason,
                "error_pct": error_pct,
                "series": series, "is_actual": False, "period_label": period_label,
                "out_of_range": False, "metric": metric, "months_ahead": 1,
                "confidence_level": "high", "confidence_reason": "this is the exact horizon that was backtested",
                "range_low": None, "range_high": None, "log": steps}

    # ---------------- Whole-business path (unchanged logic, dynamic metric check) ----------------
    series = load_series(freq, metric)
    champ = CHAMPIONS.get(metric, {}).get(horizon)
    model_name, reason, error_pct = (champ["model"], champ["reason"], champ["error_pct"]) if champ else (None, None, None)

    if horizon == "month" and target_month is not None:
        monthly = load_series("MS", metric)
        last_date = monthly.index.max()
        if target_year is None:
            resolved_year = last_date.year if target_month > last_date.month else last_date.year + 1
            _log(steps, f"no explicit year given for month={target_month} -> resolved to "
                         f"{resolved_year} relative to data ending {last_date.strftime('%B %Y')}")
        else:
            resolved_year = target_year

        target_period = pd.Timestamp(year=resolved_year, month=target_month, day=1)
        is_in_data = target_period in monthly.index
        _log(steps, f"target month = {target_period.strftime('%B %Y')}; already in data? {is_in_data}")

        if is_in_data:
            actual_value = float(monthly.loc[target_period])
            _log(steps, f"{target_period.strftime('%B %Y')} is a real recorded month -> returning actual "
                         f"{metric_label} {actual_value:,.1f}, no model run")
            return {"predicted_value": actual_value, "model_name": None,
                    "reason": f"Directly summed {metric_label} from recorded transactions for that month -- not modeled.",
                    "series": series, "is_actual": True, "period_label": target_period.strftime("%B %Y"),
                    "out_of_range": False, "metric": metric, "months_ahead": 0, "log": steps}

        if not champ:
            _log(steps, f"metric={metric!r} has no backtest at all -> refusing regardless of months_ahead")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": target_period.strftime("%B %Y"),
                    "out_of_range": True, "metric": metric, "unvalidated_metric": True, "log": steps}

        months_ahead = (target_period.year - last_date.year) * 12 + (target_period.month - last_date.month)
        _log(steps, f"running {model_name} {months_ahead} month(s) ahead to reach {target_period.strftime('%B %Y')}")
        pred, lo, hi = run_forecast_with_range(model_name, series, months_ahead, "MS",
                                                log_fn=log_fn, metric_label=metric_label)
        predicted_value = float(pred[-1])
        range_low = float(lo[-1]) if not np.isnan(lo[-1]) else None
        range_high = float(hi[-1]) if not np.isnan(hi[-1]) else None
        _log(steps, f"{target_period.strftime('%B %Y')}: {predicted_value:,.1f}"
                     + (f"  (80% range: {range_low:,.1f} - {range_high:,.1f})" if range_low else "  (no range available for this method)"))
        level, why = month_confidence_note(months_ahead)
        _log(steps, f"confidence: {level} -- {why}")
        return {"predicted_value": predicted_value, "model_name": model_name, "error_pct": error_pct,
                "reason": reason + f" Extrapolated {months_ahead} month(s) ahead to reach {target_period.strftime('%B %Y')}.",
                "series": series, "is_actual": False, "period_label": target_period.strftime("%B %Y"),
                "out_of_range": False, "metric": metric, "months_ahead": months_ahead,
                "confidence_level": level, "confidence_reason": why,
                "range_low": range_low, "range_high": range_high, "log": steps}

    if horizon == "year" and target_year is not None:
        monthly = load_series("MS", metric)
        counts = monthly.groupby(monthly.index.year).size()
        last_year, last_month = monthly.index.max().year, monthly.index.max().month
        year_is_complete = target_year in counts.index and (
            counts[target_year] == 12 if target_year < last_year
            else (target_year == last_year and last_month == 12)
        )
        _log(steps, f"data fully covers through {last_year}-{last_month:02d}; "
                     f"is {target_year} already complete in the data? {year_is_complete}")
        if year_is_complete:
            actual_value = float(monthly[monthly.index.year == target_year].sum())
            _log(steps, f"{target_year} is a real recorded year -> returning actual "
                         f"{metric_label} {actual_value:,.1f}, no model run")
            return {"predicted_value": actual_value, "model_name": None,
                    "reason": f"Directly summed {metric_label} from recorded transactions for that year -- not modeled.",
                    "series": series, "is_actual": True, "period_label": str(target_year),
                    "out_of_range": False, "metric": metric, "log": steps}

        years_ahead = target_year - last_year
        _log(steps, f"{target_year} is {years_ahead} year(s) beyond the data -> forecasting it, honestly labeled")

        if not champ:
            _log(steps, f"metric={metric!r} has no backtest at all -> refusing regardless of years_ahead")
            return {"predicted_value": None, "model_name": None, "reason": None,
                    "series": series, "is_actual": False, "period_label": str(target_year),
                    "out_of_range": True, "metric": metric, "unvalidated_metric": True, "log": steps}

        months_needed = years_ahead * 12
        _log(steps, f"running {model_name} {months_needed} months ahead "
                     f"(covers {last_year + 1} through {target_year}), then keeping only {target_year}'s 12 months")
        pred, lo, hi = run_forecast_with_range(model_name, series, months_needed, "MS",
                                                log_fn=log_fn, metric_label=metric_label)
        target_months_pred = pred[-12:]
        predicted_value = float(np.sum(target_months_pred))
        range_low = float(np.nansum(lo[-12:])) if not np.all(np.isnan(lo)) else None
        range_high = float(np.nansum(hi[-12:])) if not np.all(np.isnan(hi)) else None
        _log(steps, f"{target_year} total: {predicted_value:,.1f}"
                     + (f"  (80% range: {range_low:,.1f} - {range_high:,.1f})" if range_low else "  (no range available for this method)"))
        level, why = confidence_note(years_ahead)
        _log(steps, f"confidence: {level} -- {why}")
        return {"predicted_value": predicted_value, "model_name": model_name, "error_pct": error_pct,
                "reason": reason + f" Extrapolated {years_ahead} extra year(s) past that to reach {target_year}.",
                "series": series, "is_actual": False, "period_label": str(target_year),
                "out_of_range": False, "metric": metric, "years_ahead": years_ahead,
                "confidence_level": level, "confidence_reason": why,
                "range_low": range_low, "range_high": range_high, "log": steps}

    if not champ:
        _log(steps, f"metric={metric!r} has no backtest (validated metrics: {list(CHAMPIONS.keys())}) "
                     f"-> refusing")
        return {"predicted_value": None, "model_name": None, "reason": None,
                "series": series, "is_actual": False, "period_label": None,
                "out_of_range": True, "metric": metric, "unvalidated_metric": True, "log": steps}

    steps_ahead = 12 if horizon == "year" else 1
    _log(steps, f"running {model_name} on {len(series)} periods of history, {steps_ahead} step(s) ahead")
    pred = run_forecast(model_name, series, steps_ahead, freq, log_fn=log_fn,
                         metric_label=metric_label)
    predicted_value = float(np.sum(pred)) if horizon == "year" else float(pred[0])
    _log(steps, f"-> final predicted_value: {predicted_value:,.1f}")

    last_date = series.index.max()
    if horizon == "year":
        period_label = str(last_date.year + 1)
    elif horizon == "month":
        period_label = (last_date + pd.DateOffset(months=1)).strftime("%B %Y")
    else:
        period_label = "week of " + (last_date + pd.Timedelta(weeks=1)).strftime("%b %d, %Y")
    _log(steps, f"this forecast covers: {period_label}")

    return {"predicted_value": predicted_value, "model_name": model_name, "reason": reason,
            "error_pct": error_pct,
            "series": series, "is_actual": False, "period_label": period_label,
            "out_of_range": False, "metric": metric, "years_ahead": 1,
            "confidence_level": "high", "confidence_reason": "this is the exact horizon that was backtested",
            "range_low": None, "range_high": None, "log": steps}


def all_model_forecasts(series, steps_ahead, freq, metric_label=None, dimension=None, dimension_value=None,
                         known=None):
    """Every free (non-LLM) candidate's own prediction for the exact same target
    answer_question() already resolved -- same train series, same step count, so this is
    genuinely the same question asked of all 5 local models, not a separately-scoped run.

    Used only to LABEL the dashboard's forecast chart with what every candidate would have
    said -- the champion's own already-computed value (answer_question's predicted_value)
    stays the one actually shown/trusted; this is purely "here's what every other approach
    would have guessed instead." claude-haiku-4-5 is deliberately excluded here: it never runs
    live unless it's already the champion, and the champion's value is already known to the
    caller (see dashboard_service.get_dashboard_summary) without a second, redundant network
    call -- a model that can't produce a forecast on this little history is just omitted, not
    a fatal error for the rest.

    `known`, when given, is {model_name: value} for a result already computed by the caller
    (the champion, from answer_question) -- that one model is reused rather than re-run, since
    chronos in particular is expensive enough (a real model load + inference, not a formula)
    that running it twice for one page load is a real, measurable cost, not a rounding error."""
    known = known or {}
    out = dict(known)
    for model in ALL_MODELS:
        if model in known:
            continue
        try:
            pred = run_forecast(model, series, steps_ahead, freq, metric_label=metric_label,
                                 dimension=dimension, dimension_value=dimension_value)
            out[model] = float(np.sum(pred)) if steps_ahead > 1 else float(pred[0])
        except Exception:
            continue
    return out


# ==================================================================================
# Decline/growth attribution -- "why did X change" questions, a completely different
# computation from answer_question() above (which looks up or forecasts a single number).
# Backend-only: this is a live-app feature with no offline-backtest counterpart, so unlike
# the forecasting functions above it isn't mirrored to the root copy score_*.py scripts
# never call it. Every number below is a real, direct sum over real recorded transactions --
# no model, no LLM, nothing invented. This is the ONLY input llm_client.phrase_decline_
# explanation() ever sees; it narrates these numbers, it never computes or invents one.
# ==================================================================================

DECLINE_DRILL_DIMENSIONS = [("branch", "stock_branch"), ("category", "category"), ("product", "product")]
# Fixed order, matching how a manager naturally narrows a decline down: which branch, which
# category within it, which product within that. Drilling always goes the full depth as long as
# there's real data and the next level still moves the same direction as what's being explained
# -- it never stops early just because a level's top contributor isn't dominant. What
# DECLINE_CONCENTRATION_THRESHOLD_PCT controls is only the "concentrated" label on each level
# (see explain_decline): whether that level's top mover explains most of the movement there, or
# the movement was broadly spread -- always reported honestly, never used to cut the drill short.
DECLINE_CONCENTRATION_THRESHOLD_PCT = 30

DECLINE_TOP_N = 3
# How many siblings to keep at every fork of the fanned-out drill tree (see _decline_tree_branch
# / DeclineExplanation.tree) -- top 3 branches, top 3 categories within EACH of those branches,
# top 3 products within EACH of those categories, all shown at once. Separate from the single
# deepest path in `levels` (top 1 at each level), which is what gets narrated into prose --
# narrating a 3x3x3 fan-out in a paragraph would be unreadable, so the LLM still only ever sees
# the one clearest path; the tree is for the visual UI only.


def _decline_period_total(df_scope, metric_col, year):
    return float(df_scope.loc[df_scope["sales_date"].dt.year == year, metric_col].sum())


def _yoy_total(df_scope, metric_col, target_year, comparison_year):
    """The top-line year-over-year number alone -- (target, comparison, delta, delta_pct,
    direction) -- factored out of explain_decline() so a caller that only wants the headline
    (a dashboard KPI card, refreshed on every filter change) doesn't pay for the full
    branch/category/product drill-down every time. explain_decline() itself calls this too,
    for its own top-line total -- one implementation, not two that could drift."""
    target = _decline_period_total(df_scope, metric_col, target_year)
    comparison = _decline_period_total(df_scope, metric_col, comparison_year)
    delta = target - comparison
    delta_pct = round(delta / comparison * 100, 1) if comparison else None
    direction = "decrease" if delta < 0 else ("increase" if delta > 0 else "flat")
    return target, comparison, delta, delta_pct, direction


def compute_yoy_total(metric="net_sales", target_year=None, comparison_year=None,
                       dimension=None, dimension_value=None):
    """Public, lightweight entry point for a KPI card's "Growth %" -- reads the CSV once,
    optionally scopes to one dimension value, and returns just the top-line YoY numbers with
    no drill-down. See explain_decline() for the full "why" version of this same computation."""
    metric_col = METRIC_COLUMNS.get(metric, metric)
    if comparison_year is None:
        comparison_year = target_year - 1
    df = pd.read_csv(DATA_PATH, parse_dates=["sales_date"])
    if dimension and dimension_value:
        df = df[df[DIMENSION_COLUMNS[dimension]] == dimension_value]
    target, comparison, delta, delta_pct, direction = _yoy_total(df, metric_col, target_year, comparison_year)
    return {"target_year": target_year, "comparison_year": comparison_year,
            "target": target, "comparison": comparison, "delta": delta,
            "delta_pct": delta_pct, "direction": direction}


_GRAIN_FREQ = {"week": "W", "month": "MS", "year": "YS"}


def _period_label(ts, grain):
    if grain == "year":
        return str(ts.year)
    if grain == "month":
        return ts.strftime("%B %Y")
    return "week of " + ts.strftime("%b %d, %Y")


def compute_period_total(metric="net_sales", grain="year", dimension=None, dimension_value=None):
    """The dashboard KPI row's grain-aware sibling to compute_yoy_total -- that function only
    ever compares full calendar years (by design, matching explain_decline). This compares
    the latest period to the one before it, at whatever grain the filter bar has selected
    (week/month/year), so "Total Sales" for a month-grain view means last month's real total,
    not a running year figure.

    Reuses load_series() itself rather than re-deriving the resample: this dataset's history
    ends on a clean month/year boundary (verified against the CSV directly -- no trailing
    partial period to trim there), and load_series already trims the one grain that does have
    a real partial-edge problem (weekly, via .iloc[1:-1]) plus zero-fills a dimension value's
    genuinely-inactive periods so "latest" means the actual latest period, not silently
    skipping forward past a real zero -- one implementation of that logic, not two that could
    drift.
    """
    freq = _GRAIN_FREQ[grain]
    s = load_series(freq, metric, dimension, dimension_value)
    if len(s) < 2:
        return {"period_label": None, "comparison_label": None, "target": None,
                "comparison": None, "delta": None, "delta_pct": None, "direction": "flat"}
    target, comparison = float(s.iloc[-1]), float(s.iloc[-2])
    delta = target - comparison
    delta_pct = round(delta / comparison * 100, 1) if comparison else None
    direction = "decrease" if delta < 0 else ("increase" if delta > 0 else "flat")
    return {"period_label": _period_label(s.index[-1], grain), "comparison_label": _period_label(s.index[-2], grain),
            "target": target, "comparison": comparison, "delta": delta,
            "delta_pct": delta_pct, "direction": direction}


def compute_scope_matrix(metric="net_sales", grain="month", dimension="branch"):
    """Current-period status for EVERY value of one dimension at once -- the "how is each branch
    doing right now" view. One CSV read and a single groupby-resample rather than N separate
    compute_period_total() calls, because a 200-product dimension would otherwise mean 200 full
    reads of a 250k-row file.

    Each row also carries whether that exact scope is forecastable at this grain: whether it has
    a champion on record at all, and whether that champion cleared the reliability floor. A scope
    the system cannot honestly forecast is shown as such rather than quietly omitted.
    """
    freq = _GRAIN_FREQ[grain]
    metric_col = METRIC_COLUMNS.get(metric, metric)
    dim_col = DIMENSION_COLUMNS[dimension]

    df = pd.read_csv(DATA_PATH, parse_dates=["sales_date"], usecols=["sales_date", dim_col, metric_col])
    pivot = (df.set_index("sales_date").groupby(dim_col)[metric_col]
               .resample(freq).sum().unstack(0).fillna(0.0))
    if freq == "W":
        pivot = pivot.iloc[1:-1]  # same partial-edge-week trim load_series applies

    if len(pivot) < 2:
        return {"metric": metric, "metric_label": METRIC_LABELS.get(metric, metric), "grain": grain,
                "dimension": dimension, "period_label": None, "comparison_label": None, "rows": []}

    # Dimension-level backtests only ever covered net_sales (see score_dimensional*.py), and
    # answer_question() refuses any other metric at dimension level for exactly that reason.
    # Attaching a net_sales champion's error to a profit column would imply an accuracy figure
    # that was never measured, so for any other metric there is honestly no champion to show.
    champions = ({} if metric != "net_sales" else
                  {"week": DIMENSIONAL_WEEKLY_CHAMPIONS, "month": DIMENSIONAL_CHAMPIONS,
                   "year": DIMENSIONAL_YEARLY_CHAMPIONS}[grain].get(dimension, {}))

    current, previous = pivot.iloc[-1], pivot.iloc[-2]
    rows = []
    for value in pivot.columns:
        target, comparison = float(current[value]), float(previous[value])
        delta = target - comparison
        champ = champions.get(value)
        error_pct = champ.get("error_pct") if champ else None
        rows.append({
            "value": str(value),
            "target": target,
            "comparison": comparison,
            "delta": delta,
            "delta_pct": round(delta / comparison * 100, 1) if comparison else None,
            "direction": "decrease" if delta < 0 else ("increase" if delta > 0 else "flat"),
            "champion_model": champ["model"] if champ else None,
            "champion_error_pct": error_pct,
            "forecastable": bool(champ) and (error_pct is None
                                              or error_pct <= DIMENSIONAL_MAX_RELIABLE_ERROR_PCT),
        })

    rows.sort(key=lambda r: -r["target"])
    return {
        "metric": metric, "metric_label": METRIC_LABELS.get(metric, metric), "grain": grain,
        "dimension": dimension,
        "period_label": _period_label(pivot.index[-1], grain),
        "comparison_label": _period_label(pivot.index[-2], grain),
        "rows": rows,
    }


def _decline_breakdown(df_scope, dim_col, metric_col, target_year, comparison_year):
    """Every real value of dim_col present in df_scope -> target/comparison totals, delta,
    delta_pct -- sorted ascending by ₹ delta (biggest drop first, biggest gain last), so a
    caller picks index 0 for a decline or -1 for growth from the same ranked list. Ranked by
    absolute delta, not delta_pct: a product down/up 90% on ₹500 total barely matters against
    a branch down/up 8% on ₹8M -- ₹ is what actually explains the total move, percentage alone
    can be misleading either way."""
    rows = []
    for value in sorted(df_scope[dim_col].dropna().unique()):
        sub = df_scope[df_scope[dim_col] == value]
        target = _decline_period_total(sub, metric_col, target_year)
        comparison = _decline_period_total(sub, metric_col, comparison_year)
        delta = target - comparison
        delta_pct = round(delta / comparison * 100, 1) if comparison else None
        rows.append({"value": str(value), "target": round(target, 1), "comparison": round(comparison, 1),
                      "delta": round(delta, 1), "delta_pct": delta_pct})
    rows.sort(key=lambda r: r["delta"])
    return rows


def _decline_driver_breakdown(final_scope, metric_col, target_year, comparison_year):
    """Quantity / avg price / distinct customers breakdown for one fully-scoped leaf --
    explains WHY that specific value moved: fewer units sold, a price/discount shift, or fewer
    distinct customers. Factored out so both explain_decline()'s single deepest-path driver and
    _decline_tree_branch()'s per-leaf drivers use identical logic, not two copies that could
    drift."""
    target_rows = final_scope[final_scope["sales_date"].dt.year == target_year]
    comparison_rows = final_scope[final_scope["sales_date"].dt.year == comparison_year]
    qty_t, qty_c = float(target_rows["quantity"].sum()), float(comparison_rows["quantity"].sum())
    rev_t, rev_c = float(target_rows[metric_col].sum()), float(comparison_rows[metric_col].sum())
    cust_t, cust_c = int(target_rows["customer_id"].nunique()), int(comparison_rows["customer_id"].nunique())
    price_t = (rev_t / qty_t) if qty_t else None
    price_c = (rev_c / qty_c) if qty_c else None

    def _dpct(t, c):
        return round((t - c) / c * 100, 1) if c not in (None, 0) and t is not None else None

    driver = {
        "quantity": {"target": qty_t, "comparison": qty_c, "delta_pct": _dpct(qty_t, qty_c)},
        "avg_price": {"target": round(price_t, 2) if price_t is not None else None,
                      "comparison": round(price_c, 2) if price_c is not None else None,
                      "delta_pct": _dpct(price_t, price_c)},
        "distinct_customers": {"target": cust_t, "comparison": cust_c, "delta_pct": _dpct(cust_t, cust_c)},
    }
    candidates = {k: abs(v["delta_pct"]) for k, v in driver.items() if v["delta_pct"] is not None}
    driver["primary_driver"] = max(candidates, key=candidates.get) if candidates else None
    return driver


def _decline_tree_branch(scope_df, drill_dims, metric_col, target_year, comparison_year,
                          is_decrease, top_n, log_fn, path_desc=""):
    """The fanned-out counterpart to explain_decline()'s single-path walk: at drill_dims[0],
    keep the top `top_n` movers in the direction being explained (not just the single best),
    and for EACH of them, recurse into drill_dims[1:] within that value's own scope -- so a
    3-wide fan at the branch level produces up to 3x3=9 categories, then up to 9x3=27 products,
    every one of them a real, independently computed number.

    Returns [] whenever there's honestly nothing to attribute here (no data at this scope, or
    every value at this level moved the opposite direction) -- same "stop honestly, don't force
    a path" rule explain_decline() itself follows, just applied per-branch instead of once."""
    if not drill_dims:
        return []
    dim_name, dim_col = drill_dims[0]
    breakdown = _decline_breakdown(scope_df, dim_col, metric_col, target_year, comparison_year)
    if not breakdown:
        return []
    parent_delta = sum(r["delta"] for r in breakdown)
    same_direction_total = sum(r["delta"] for r in breakdown
                                if (r["delta"] < 0 if is_decrease else r["delta"] > 0))
    if not same_direction_total:
        return []  # nothing at this fork moved the direction being explained -- honest stop

    offset_note = None
    if (is_decrease and parent_delta > same_direction_total) or \
       (not is_decrease and parent_delta < same_direction_total):
        offset = abs(parent_delta - same_direction_total)
        opposite = "growth" if is_decrease else "decline"
        offset_note = (f"{offset:,.1f} of {opposite} elsewhere at this level partly offset it "
                        f"(net {dim_name}-level change was {parent_delta:,.1f})")

    ranked = breakdown if is_decrease else list(reversed(breakdown))
    top = [r for r in ranked if (r["delta"] < 0 if is_decrease else r["delta"] > 0)][:top_n]

    nodes = []
    for r in top:
        share = round(r["delta"] / same_direction_total * 100, 1)
        here = f"{path_desc}{dim_name}={r['value']}"
        child_scope = scope_df[scope_df[dim_col] == r["value"]]
        children = _decline_tree_branch(child_scope, drill_dims[1:], metric_col, target_year, comparison_year,
                                         is_decrease, top_n, log_fn, path_desc=f"{here} -> ")
        node = {
            "dimension": dim_name, "value": r["value"], "target": r["target"], "comparison": r["comparison"],
            "delta": r["delta"], "delta_pct": r["delta_pct"], "share_of_parent_decline_pct": share,
            "concentrated": share >= DECLINE_CONCENTRATION_THRESHOLD_PCT, "offset_note": offset_note,
            "all_values": breakdown, "children": children, "stopped_reason": None, "driver": None,
        }
        if len(drill_dims) == 1:
            node["driver"] = _decline_driver_breakdown(child_scope, metric_col, target_year, comparison_year)
        elif not children:
            node["stopped_reason"] = f"no {drill_dims[1][0]} data moving the same direction within {here}"
        nodes.append(node)
    log_fn(f"tree fork {path_desc or '(root)'}{dim_name}: {len(breakdown)} real values, "
           f"kept top {len(top)} of the {len([r for r in ranked if (r['delta'] < 0 if is_decrease else r['delta'] > 0)])} "
           f"moving {'down' if is_decrease else 'up'}")
    return nodes


def explain_decline(metric="net_sales", target_year=None, comparison_year=None,
                     dimension=None, dimension_value=None, log_fn=None):
    """Real, verified branch -> category -> product drill-down explaining the change in
    `metric` from comparison_year to target_year (default: the immediately prior year).

    dimension/dimension_value optionally pre-scope the analysis (e.g. "why did Medical Branch
    05 decline" starts already filtered to that branch, checking ITS total, then drilling
    category -> product within it -- the same mechanism, just starting one level in). Whole-
    business net_sales/profit never actually declined year-over-year anywhere in this dataset
    (every year grew) -- individual branches/categories/products can and do decline even while
    the total grows, which is exactly why scoped questions matter, not just whole-business ones.

    Works symmetrically for growth, not just decline -- "why did sales increase" gets the same
    real drill-down, just finding the biggest GAIN at each level instead of the biggest drop.
    Only a genuinely flat/zero change skips drilling (nothing moved to attribute).

    Returns a dict -- never raises for a business-rule outcome (a flat change, a broadly-spread
    move, missing data at some level are all valid, honestly reported results, not errors).
    "levels" holds only the concentrated path actually drilled;
    each level's "all_values" carries the FULL ranked breakdown at that scope, for transparency
    (mirrors how champion tables are exposed elsewhere) -- never sent to the LLM in full, only
    the drilled path and totals are (see llm_client.phrase_decline_explanation).
    """
    log_fn = log_fn or (lambda m: None)
    metric_col = METRIC_COLUMNS.get(metric, metric)
    metric_label = METRIC_LABELS.get(metric, metric)
    if comparison_year is None:
        comparison_year = target_year - 1
    log_fn(f"explain_decline: metric={metric!r} target_year={target_year} comparison_year={comparison_year} "
           f"scope={dimension}={dimension_value!r}")

    df = pd.read_csv(DATA_PATH, parse_dates=["sales_date"])
    drill_dims = DECLINE_DRILL_DIMENSIONS
    if dimension and dimension_value:
        df = df[df[DIMENSION_COLUMNS[dimension]] == dimension_value]
        # Don't re-derive the same dimension we already scoped to -- drilling "which value of
        # branch is worst" within a single already-chosen branch is trivially 100%, not a finding.
        drill_dims = [(d, c) for d, c in DECLINE_DRILL_DIMENSIONS if d != dimension]

    total_target, total_comparison, total_delta, total_delta_pct, direction = \
        _yoy_total(df, metric_col, target_year, comparison_year)
    log_fn(f"whole business: {comparison_year}={total_comparison:,.1f} -> {target_year}={total_target:,.1f} "
           f"({total_delta_pct}% -> {direction})")

    levels, stopped_reason = [], None
    if direction == "flat":
        stopped_reason = f"{metric_label} did not meaningfully change from {comparison_year} to {target_year}"
    else:
        # Symmetric for either direction: a decrease drills into the biggest DROP at each
        # level, an increase drills into the biggest GAIN -- same mechanism, same concentration
        # check, same offsetting logic, just picking from the opposite end of the same ranked
        # breakdown (which is always sorted ascending by delta). Growth deserves the same real,
        # verified "what actually drove it" answer a decline gets, not just the top-line number.
        is_decrease = direction == "decrease"
        scope_df = df
        for dim_name, dim_col in drill_dims:
            breakdown = _decline_breakdown(scope_df, dim_col, metric_col, target_year, comparison_year)
            if not breakdown:
                stopped_reason = f"no {dim_name} data at this scope"
                break
            parent_delta = sum(r["delta"] for r in breakdown)
            if (is_decrease and parent_delta >= 0) or (not is_decrease and parent_delta <= 0):
                stopped_reason = f"{dim_name} level did not {direction} overall at this scope"
                break
            top = breakdown[0] if is_decrease else breakdown[-1]
            # Share of the movement in THIS direction specifically, not of the net parent delta
            # -- if some values moved the opposite way, net parent_delta can be much smaller in
            # magnitude than the top single mover, which once made a decrease's share exceed
            # 100% (observed live: 501.5% for Medical Branch 02, where Neurology dropped ₹56K
            # but other categories grew ₹45K, netting the branch to only -₹11K). same_direction_
            # total sums ONLY the values that moved the same way as the overall change, so the
            # top one's share of THAT is always well-defined between 0% and 100%.
            same_direction_total = sum(r["delta"] for r in breakdown
                                        if (r["delta"] < 0 if is_decrease else r["delta"] > 0))
            share = round(top["delta"] / same_direction_total * 100, 1) if same_direction_total else 0.0
            offset_note = None
            # is_decrease: both <= 0, net less negative than the decline-only sum -> growth offset it.
            # increase: both >= 0, net less positive than the growth-only sum -> decline offset it.
            if (is_decrease and parent_delta > same_direction_total) or \
               (not is_decrease and parent_delta < same_direction_total):
                offset = abs(parent_delta - same_direction_total)
                opposite = "growth" if is_decrease else "decline"
                offset_note = (f"{offset:,.1f} of {opposite} elsewhere at this level partly offset it "
                                f"(net {dim_name}-level change was {parent_delta:,.1f})")
            log_fn(f"{dim_name} breakdown ({len(breakdown)} values): top={top['value']} "
                   f"delta={top['delta']:,.1f} ({share}% of this level's total {direction})")
            # Always keep drilling to the full hierarchy (branch -> category -> product) as long
            # as there's real data and the next level still moves the same direction as what
            # we're explaining -- low concentration is reported honestly (concentrated=False,
            # same as offset_note already was), never used to stop early. A branch that's only
            # 20.9% of the movement is still real, useful detail; hiding the deeper drill-down
            # because it isn't THE dominant story was less informative, not more honest.
            concentrated = share >= DECLINE_CONCENTRATION_THRESHOLD_PCT
            levels.append({"dimension": dim_name, "value": top["value"], "target": top["target"],
                            "comparison": top["comparison"], "delta": top["delta"],
                            "delta_pct": top["delta_pct"], "share_of_parent_decline_pct": share,
                            "concentrated": concentrated, "offset_note": offset_note, "all_values": breakdown})
            scope_df = scope_df[scope_df[dim_col] == top["value"]]

    driver = None
    if levels and levels[-1]["dimension"] == "product" and stopped_reason is None:
        # Reached the bottom of the fixed hierarchy (real data + same-direction movement all the
        # way down -- concentration doesn't gate this anymore, see the loop above) --
        # break down WHY that specific product (within that branch+category) moved: fewer units
        # sold, a price/discount shift, or fewer distinct customers. Purely computed, same as
        # everything above; phrase_decline_explanation only narrates which moved most.
        final_scope = df
        for lvl in levels:
            final_scope = final_scope[final_scope[DIMENSION_COLUMNS[lvl["dimension"]]] == lvl["value"]]
        driver = _decline_driver_breakdown(final_scope, metric_col, target_year, comparison_year)
        log_fn(f"driver breakdown: qty {driver['quantity']['comparison']:,.0f}->{driver['quantity']['target']:,.0f}, "
               f"avg_price {driver['avg_price']['comparison']}->{driver['avg_price']['target']}, "
               f"customers {driver['distinct_customers']['comparison']}->{driver['distinct_customers']['target']}, "
               f"primary={driver['primary_driver']}")

    # The fanned-out top-DECLINE_TOP_N-at-every-fork tree, for the visual "show me more than
    # just the single biggest path" drill-down UI -- independent walk from the same starting
    # scope/direction, never affects `levels`/`driver` above (which stay the single clearest
    # path the LLM narrates into prose).
    tree = []
    if direction != "flat":
        tree = _decline_tree_branch(df, drill_dims, metric_col, target_year, comparison_year,
                                     is_decrease, DECLINE_TOP_N, log_fn)
        log_fn(f"tree: {len(tree)} top-level {drill_dims[0][0]} nodes fanned out "
               f"(top {DECLINE_TOP_N} at every fork)")

    return {
        "metric": metric, "metric_label": metric_label,
        "target_year": target_year, "comparison_year": comparison_year,
        "scope_dimension": dimension, "scope_value": dimension_value,
        "total": {"target": round(total_target, 1), "comparison": round(total_comparison, 1),
                  "delta": round(total_delta, 1), "delta_pct": total_delta_pct},
        "direction": direction, "levels": levels, "stopped_reason": stopped_reason, "driver": driver,
        "tree": tree,
    }
